### ISSUE TITLE
Save as button should be disabled for EmptyTab

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1282]
__Describe the Bug__

Save as button is enabled for empty tab and it causes an unhandled Promise rejection on backend. The issue did not occur in Camunda Modeler 2.2.4.

![screenshot 2019-03-04 at 11 35 51](https://user-images.githubusercontent.com/28307541/53728271-a1027f00-3e72-11e9-89b6-5717a9bdc1f9.png)

__Steps to Reproduce__

1. Open Camunda Modeler and close all tabs.
2. Click on save as button.

There is an unhandled Promise rejection on backend, see log below:

```
(node:76526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
    at /Users/maciej.barelkowski/workspace/bpmn-io/camunda-modeler/app/lib/index.js:169:12
    at EventEmitter.<anonymous> (/Users/maciej.barelkowski/workspace/bpmn-io/camunda-modeler/app/lib/util/renderer.js:39:14)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Users/maciej.barelkowski/workspace/bpmn-io/camunda-modeler/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:285:13)
    at WebContents.emit (events.js:182:13)
(node:76526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:76526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
app:main window focused
```

</details>

__Expected Behavior__

Button should be disabled and no message to backend should be sent.

__Environment__

 - OS: MacOS
 - Camunda Modeler Version: `master`

**Comment by pinussilvestrus** [comment]
Closed via #1285
