### ISSUE TITLE
I saw an UncaughtException when opening the application

### ISSUE THREAD

**Issue by sebwarnke** [camunda/camunda-modeler#1381]
Steps to Reproduce:
- Start Modeler by clicking the icon in MacOS

Result:
Popup window showing:
```
Uncaught Exception:
TypeError: path.basename is not a function
    at filePaths.map.path (/Applications/Camunda Modeler.app/Contents/Resources/app.asar/lib/index.js:320:20)
    at Array.map (<anonymous>)
    at App.app.openFiles (/Applications/Camunda Modeler.app/Contents/Resources/app.asar/lib/index.js:314:35)
    at App.<anonymous> (/Applications/Camunda Modeler.app/Contents/Resources/app.asar/lib/index.js:254:9)
    at App.emit (events.js:182:13)
    at /Applications/Camunda Modeler.app/Contents/Resources/app.asar/lib/index.js:263:7
    at EventEmitter.<anonymous> (/Applications/Camunda Modeler.app/Contents/Resources/app.asar/lib/util/renderer.js:42:14)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/Applications/Camunda Modeler.app/Contents/Resources/electron.asar/browser/api/web-contents.js:285:13)
    at WebContents.emit (events.js:182:13)
```

__Environment__

 - OS: MacOS 10.14.5 (18F132)
 - Camunda Modeler Version: 3.1.0

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/1382.
