### ISSUE TITLE
Undoing participant paste crashes BPMN editor with "Cannot read property 'parentNode' of undefined" 

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#1617]
__Describe the Bug__

When undoing pasting of a participant with lanes it can happen that the BPMN editor crashes / becomes unusable. The app reports the following trace:

```
Cannot read property 'parentNode' of undefined
    at file:///Downloads/camunda-modeler-3.5.0-linux-x64/resources/app.asar/public/6.6.js:1:375923
    at iterator (webpack:///node_modules/diagram-js/node_modules/min-dash/dist/index.esm.js:145:0)
    at file:///Downloads/camunda-modeler-3.5.0-linux-x64/resources/app.asar/public/6.6.js:1:375872
    at iterator (webpack:///node_modules/diagram-js/node_modules/min-dash/dist/index.esm.js:145:0)
    at parents (webpack:///node_modules/diagram-js/lib/core/GraphicsFactory.js:156:9)
    at file:///Downloads/camunda-modeler-3.5.0-linux-x64/resources/app.asar/public/6.6.js:1:604837
    at file:///Downloads/camunda-modeler-3.5.0-linux-x64/resources/app.asar/public/2.2.js:1:17172
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:366:0)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:351:0)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:312:0) [ error ]
```

__Steps to Reproduce__

1. Open [test diagram](https://github.com/camunda/camunda-modeler/files/3901655/test.bpmn.txt)
2. Copy participant with children
3. Paste participant with children
4. Undo
5. Try to interact with the modeling canvas
6. See the error shown above pop up

__Expected Behavior__

* Undoing does not lead to the editor blowing up.

__Environment__

 - OS: Any
 - Camunda Modeler Version: v3.5.0, v3.4.1, v3.3.5

**Comment by nikku** [comment]
This may be related, however it does not fix the issue. I can still reproduce it on `bpmn-js@master`.
