### ISSUE TITLE
Diagram cannot be opened with plugins enabled

### ISSUE THREAD

**Issue by r-hound** [camunda/camunda-modeler#1756]
__Any diagram crashes with tokenSimulation plug-in installed__
downloaded new Camunda Modeler 3.7.1 zip for Win x64, trying to open any existing diagram. 
file is not rendered
Getting the following message in the console:
[D:\DEV\diagram_realty.bpmn] undo is already registered
    at r (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:257:9)
    at error (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:216:10)
    at _registerAction (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:200:16)
    at register (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:79:9)
    at call (webpack:///node_modules/bpmn-js/lib/features/editor-actions/BpmnEditorActions.js:38:50)
    at file:///D:/camunda-modeler/resources/app.asar/public/1.1.js:1:61694
    at file:///D:/camunda-modeler/resources/app.asar/public/1.1.js:1:50614
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

__Steps to Reproduce__

1. select bpmn file, right click
2. open with... select Camunda Modeler.exe
3. getting "Ooops, this shouln't have happened" and the following  [D:\DEV\some-process.bpmn] undo is already registered
    at r (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:257:9)
    at error (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:216:10)
    at _registerAction (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:200:16)
    at register (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:79:9)
    at call (webpack:///node_modules/bpmn-js/lib/features/editor-actions/BpmnEditorActions.js:38:50)
    at file:///D:/camunda-modeler/resources/app.asar/public/1.1.js:1:61694
    at file:///D:/camunda-modeler/resources/app.asar/public/1.1.js:1:50614
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

4. clicking on disable plug-ins helps, but only untill the next restart, 
5. deleting the tokenSimulation plugin helped also

__Expected Behavior__

Diagram opened and rendered sucessfully.

__Environment__

- OS:  Windows 10
- Camunda Modeler Version: 3.7.1

**Comment by pinussilvestrus** [comment]
Can you share what plugins you're using so we might able to reproduce it?

**Comment by r-hound** [comment]
Hello! 
Only stock - tokenSimulation, which was bundled with the modeler. No other plug-ins used. Please find attached a zip with plugin and a sample diargram which failed to open
[DEV.zip](https://github.com/camunda/camunda-modeler/files/4426762/DEV.zip)

**Comment by nikku** [comment]
To double-check: You are using the _latest_ version of the token simulation? Or some older variant?

**Comment by r-hound** [comment]
I used the one, which was bundelled with camunda modeler 3.7.1.
I downloaded the modeler, unzipped it to empty folder, tryed to open my file. got OOPS. no custom plug-ins, no version substitution, just 3.7.1 "as is".

**Comment by pinussilvestrus** [comment]
We never bundle any kind of external plugin into a Modeler version, plugins have to be installed separately. 

What Nico means is what version of the Token Simulation Plugin you're using, not which Modeler version. You can read in our [plugins documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/plugins#plugging-into-the-camunda-modeler) where to find your installed plugins.

**Comment by r-hound** [comment]
Hmm... sorry, it wasn't an empty folder, I really had an old Modeler with Token Simulator plugin v0.1.0 previously installed.

**Comment by nikku** [comment]
In this case, please update to the latest version of the token simulation plug-in.
