### ISSUE TITLE
Error when I undo multiple times in the documentation field of bpmn-js-properties-panel

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#1830]
__Describe the Bug__

Error when I undo multiple times in the documentation field of bpmn-js-properties-panel.

Sentry Issue: [CAMUNDA-MODELER-K](https://sentry.io/organizations/camunda-modeling/issues/1674407138/?referrer=github_integration)

```
Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 11 is larger than the node's length (9).

IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 11 is larger than the node's length (9).
```

__Steps to Reproduce__

1. Type in the documentation field with multiple enters
2. Press undo shortcut (Cmd+Z on MacOS) multiple times so that the field is empty
3. now this happens

__Expected Behavior__

No errors.

__Environment__

- OS: MacOS
- Camunda Modeler Version: v4.0.0

<details><summary>LOG</summary>

```
2020-06-09T13:44:58.837Z  ERROR client [diagram_1.bpmn] Failed to execute 'setStart' on 'Range': The offset 8 is larger than the node's length (6).
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:104967
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:105063
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:105117
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:105123
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:83065
    at collection (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:14)
    at forEach (webpack:///node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js:886:2)
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:106112
    at iteratee (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:8)
    at collection (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:14)
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:105616
    at iteratee (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:8)
    at collection (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:14)
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:105552
    at iteratee (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/_arrayEach.js:15:8)
    at collection (webpack:///node_modules/bpmn-js-properties-panel/node_modules/lodash/forEach.js:38:14)
    at forEach (webpack:///node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js:987:2)
    at _updateActivation (webpack:///node_modules/bpmn-js-properties-panel/lib/PropertiesPanel.js:479:9)
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/5.5.js:1:98395
    at file:///Applications/Camunda%20Modeler%204.0.0.app/Contents/Resources/app.asar/public/2.2.js:1:43672
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:455:19)
    at _popAction (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:230:9)
    at undo (webpack:///src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/PropertiesPanelKeyoardBindings.js:57:45)
    at apply (webpack:///node_modules/@sentry/browser/esm/helpers.js:71:22)
```
</details>

**Comment by barmac** [comment]
I cannot reproduce it anymore. Not sure when it was fixed.

**Comment by barmac** [comment]
No milestone because I can't tell when we fixed that.
