### ISSUE TITLE
cannot add output rule: error "cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by grexe** [camunda/camunda-modeler#1914]
__Describe the Bug__

There seems to be an issue with older DMN 1.0 diagrams being edited in latest modeller 4.2.0 (didn't use the auto migration feature here I think).
Trying to add an output column produced an error, but adding a rule worked:
```
Cannot read property 'length' of undefined
    at length (webpack:///node_modules/dmn-js-decision-table/lib/features/editor-actions/DecisionTableEditorActions.js:125:15)
    at opts (webpack:///node_modules/table-js/lib/features/editor-actions/EditorActions.js:86:35)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:353859
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/2.2.js:1:45005
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:365:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:350:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:311:23)
    at fire (webpack:///node_modules/dmn-js-decision-table/lib/features/add-input-output/components/AddOutput.js:48:22)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:352489
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/6.6.js:8:207685
    at event (webpack:///node_modules/inferno/dist/index.esm.js:465:23)
    at apply (webpack:///node_modules/@sentry/browser/esm/helpers.js:71:22) [ error ]
```

__Steps to Reproduce__

1. open a DMN 1.0 file with a decision table with input and output parameters
2. press "+" to add an output
3. an error is produced in the log, nothing happens

__Expected Behavior__

a new output parameter column should be added to the right in the table.

__Environment__

- OS: MacOS X 10.15.6 (19G73)
- Camunda Modeler Version: 4.2.0

**Comment by grexe** [comment]
attaching a sample (please rename extension to `.dmn` - this is restricted here, so I chose `.txt`, stupid, non-MIME-type sniffing parser;-)
[broken-dmn.txt](https://github.com/camunda/camunda-modeler/files/5070313/broken-dmn.txt)

**Comment by pinussilvestrus** [comment]
Why would you use DMN 1.0 files in 4.x modeler versions? I think we only support DMN 1.3 files beginning with 4.0.

**Comment by philippfromme** [comment]
You cannot open a DMN 1.0 diagram in Camunda Modeler v4.2.0. How did you manage to add an output?
