### ISSUE TITLE
Undo of invalid process ID in the XML does not work

### ISSUE THREAD

**Issue by andreasgeier** [camunda/camunda-modeler#1925]
__Describe the Bug__

When a user set the process ID in the XML to an invalid state, get the error message modal and set back the ID to the original (valid) value, the diagram disappears and is not editable anymore. Also, the XML is no longer accessible.

__Steps to Reproduce__

1. Open the Modeler
2. Open a new BPMN diagram
3. Go to the XML view
4. Change the process ID to an invalid state (e.g. by adding a blank space)
5. Trigger the validation by trying to go back to the diagram view
6. Close the validation message modal
7. Set the ID back to the previous value (or use undo)
8. Go to the diagram view

__Expected Behavior__

Since the XML was set back to the correct state, the diagram should just be visible and editable as before.

__Environment__

- OS: MacOS 10.15.6
- Camunda Modeler Version: 4.2.0

**Comment by philippfromme** [comment]
I can reproduce this. The following error message appears in the log:

```
[diagram_3.bpmn] unparsable content <bpmn:process> detected
	line: 2
	column: 2
	nested error: illegal ID <Process_ 1xt4u8p> [ warning ]
[diagram_3.bpmn] unresolved reference <Process_1xt4u8p> [ warning ]
[diagram_3.bpmn] unresolved reference <StartEvent_1> [ warning ]
[diagram_3.bpmn] no bpmnElement referenced in <bpmndi:BPMNPlane id="BPMNPlane_1" /> [ warning ]
[diagram_3.bpmn] no bpmnElement referenced in <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" /> [ warning ]
[diagram_3.bpmn] no process or collaboration to display
    at Object.handleDefinitions (webpack:///node_modules/bpmn-js/lib/import/BpmnTreeWalker.js:198:14)
    at file:///C:/Users/phili/Downloads/camunda-modeler-4.2.0-win-x64/resources/app.asar/public/5.5.js:1:356935
    at file:///C:/Users/phili/Downloads/camunda-modeler-4.2.0-win-x64/resources/app.asar/public/5.5.js:1:356958
    at new Promise (<anonymous>)
    at F (webpack:///node_modules/bpmn-js/lib/import/Importer.js:72:9)
    at file:///C:/Users/phili/Downloads/camunda-modeler-4.2.0-win-x64/resources/app.asar/public/5.5.js:1:362018
    at new Promise (<anonymous>)
    at A.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:286:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Users/phili/Downloads/camunda-modeler-4.2.0-win-x64/resources/app.asar/public/5.5.js:1:361502
    at new Promise (<anonymous>)
    at A.<anonymous> (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:228:9)
    at apply (webpack:///node_modules/bpmn-js/lib/util/CompatibilityUtil.js:50:17)
    at file:///C:/Users/phili/Downloads/camunda-modeler-4.2.0-win-x64/resources/app.asar/public/5.5.js:1:360771 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/7f547fd2f7302c45f04d7c4c5b3e2f0ac80dfdbd
