### ISSUE TITLE
TypeError: Cannot read property 'extensionElements' of undefined

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2001]
Sentry Issue: [CAMUNDA-MODELER-H](https://sentry.io/organizations/camunda-modeling/issues/1673760145/?referrer=github_integration)

```
TypeError: Cannot read property 'extensionElements' of undefined
  at addStyle (~/build/client-bundle.js:124:71)
  at None (~/build/client-bundle.js:44:13)
  at None (~/build/client-bundle.js:2153:43)
```

**Comment by pinussilvestrus** [comment]
The error indicates coming from a plugin since `client-bundle` is nothing we provide in our code base. I tried out the listed plugins but wasn't able to reproduce it.

**Comment by pinussilvestrus** [comment]
I debugged it and was able to reproduce the error coming from [this plugin](https://github.com/umb/camunda-modeler-property-info-plugin/blob/master/client/PropertyInfoPlugin.js#L123). It happens when you try to trigger the plugin's overlays for a participant which does not have a referenced process (which hardly possible from the Modeler).

Since it's not something we maintain, we should ignore this error.
