### ISSUE TITLE
Plugin example

### ISSUE THREAD

**Issue by Flubberwurm13** [camunda/camunda-modeler#2009]
__Describe the Bug__

[diagram_1.bpmn] Cannot read property 'traits' of undefined
    at traits (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:470:31)
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at type (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:467:10)
    at registerType (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:416:9)
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at pkg (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:415:10)
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at packages (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:391:10)
    at de.g (webpack:///node_modules/bpmn-moddle/node_modules/moddle/dist/index.esm.js:715:18)
    at call (webpack:///node_modules/bpmn-moddle/dist/index.esm.js:15:9) [ error ]

__Steps to Reproduce__
1. run this example: https://github.com/camunda/camunda-modeler-plugins/tree/master/bpmn-js-plugin-moddle-extension-example
2. add example in to the plugins folder
3. Start camunda modeler
4. New BPMN diagram

__Environment__

- OS: [ Windows 10]
- Camunda Modeler Version: [e.g. 4.4.0]

**Comment by nikku** [comment]
Which example should we run?

**Comment by Flubberwurm13** [comment]
Soory. Just forgot to add: https://github.com/camunda/camunda-modeler-plugins/tree/master/bpmn-js-plugin-moddle-extension-example

**Comment by nikku** [comment]
I can run the example without any issue on Camunda Modeler v4.4.0 given the steps to reproduce you provided.

![capture kVVBvC_optimized](https://user-images.githubusercontent.com/58601/98817696-cbb81f80-242a-11eb-85fc-1c15de0c00f2.gif)

**Comment by nikku** [comment]
It also validates correctly if a diagram with a wrong extension usage comes around the corner: 

![image](https://user-images.githubusercontent.com/58601/98817896-1f2a6d80-242b-11eb-8365-ebdf3c1d7599.png)

**Comment by Flubberwurm13** [comment]
I changed the qa.json to this:


[BA-Erweiterung.zip](https://github.com/camunda/camunda-modeler/files/5524451/BA-Erweiterung.zip)

**Comment by nikku** [comment]
You understand that it is a waste of my time to open an issue like this, without pointing to your changes to lead to this bug?

To fix your issue, revise your extension, start small and see at which point it breaks.
