### ISSUE TITLE
Templates located in .camunda/element-templates directory are not listed

### ISSUE THREAD

**Issue by szerie** [camunda/camunda-modeler#2012]
__Describe the Bug__

According to documentation (available at: https://github.com/camunda/camunda-modeler/tree/master/docs/element-templates):

> Store element templates as .json file in the resources/element-templates folder, relative to the modelers executable or relative to the modelers data directory (see below). Alternatively, they can be stored in a .camunda/element-templates directory that resides, relative to the currently opened diagram, anywhere in the diagrams path hierarchy.

Unfortunately Camunda Modeler version 4.4.0 is displaying templates only from location: \resources\element-templates
![CamundaModeler44OpenTemplate](https://user-images.githubusercontent.com/57395064/98904601-32384e80-24ba-11eb-99da-925e2f938b4a.PNG)

If templates are located only in .camunda/element-templates then no template is available:
![CamundaModeler44OpenTemplate2](https://user-images.githubusercontent.com/57395064/98904645-4b40ff80-24ba-11eb-90ac-c8a32c5f31c5.PNG)

But if templates will be located in both directories then logs contains templates conflicts so in this case modeler is loading templates from both location. For example:

```
[C:\Camunda\bugTest1.bpmn] template id <TestTask> already used
    at e.exports._logError (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:284:12)
    at _logError (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:107:18)
    at _validateTemplate (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:71:19)
    at Array.forEach (<anonymous>)
    at forEach (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:56:16)
    at addAll (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/ElementTemplatesLoader.js:74:34)
    at setTemplates (webpack:///src/app/tabs/bpmn/BpmnEditor.js:202:20)
    at async (webpack:///src/app/tabs/bpmn/BpmnEditor.js:135:4) [ error ]
```

__Steps to Reproduce__

1. Insert any template to .camunda\element-templates location.
2. Run Camunda Modeler 4.4.0, and create task with appropriate type (so the applicable template was created in previous step).
3. Click "Open Catalog" to list templates - no template is visible.
4. Copy .json file with template to resources\element-templates location.
5. Click "Open Catalog" to list templates - template will be visible. Apply it on the task.
6. Save the diagram and close Camunda Modeler.
7. Open Camunda Modeler again and load previously saved .bpmn diagram.
8. Observe logs containing errors caused by templates conflicts.

__Expected Behavior__

Camunda Modeler should always use declared templates locations. Templates located in .camunda\element-templates should be visible on the list displayed after "Open Catalog" button click.

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.4.0

**Comment by nikku** [comment]
Thanks for your comprehensive bug report. This should continue to work in v4.4.0+. We'll investigate.
