### ISSUE TITLE
An I/O error occurred while sending to the backend

### ISSUE THREAD

**Issue by dostalradim** [camunda/camunda-modeler#2027]
Hi, my Camunda instance is dying on this exception. Is there some parameters which I can set to resolve this issue? The queries are not always same in this exception. My version is 7.12.0 and I use official camunda docker image.

Thank you

```
   262 03-Dec-2020 13:39:45.035 SEVERE [http-nio-8080-exec-7] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context:
   263 ### Error querying database.  Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
   264 ### The error may exist in org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
   265 ### The error may involve org.camunda.bpm.engine.impl.persistence.entity.HistoricProcessInstanceEntity.selectHistoricProcessInstancesByQueryCriteria-Inline
   266 ### The error occurred while setting parameters
   267 ### SQL: select distinct RES.*                 from (      SELECT SELF.*, DEF.NAME_, DEF.VERSION_     FROM ACT_HI_PROCINST SELF      LEFT JOIN ACT_RE_PROCDEF DEF     ON SELF.PROC_DEF_ID_ = DEF.ID_                                                                                             WHERE  (         1 = 1 and            SELF.PROC_INST_ID_ in               (                 ?               )                )       ) RES          order by RES.ID_ asc     LIMIT ? OFFSET ?
   268 ### Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
   269         org.apache.ibatis.exceptions.PersistenceException:
   270 ### Error querying database.  Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
   271 ### The error may exist in org/camunda/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
   272 ### The error may involve org.camunda.bpm.engine.impl.persistence.entity.HistoricProcessInstanceEntity.selectHistoricProcessInstancesByQueryCriteria-Inline
   273 ### The error occurred while setting parameters
   274 ### SQL: select distinct RES.*                 from (      SELECT SELF.*, DEF.NAME_, DEF.VERSION_     FROM ACT_HI_PROCINST SELF      LEFT JOIN ACT_RE_PROCDEF DEF     ON SELF.PROC_DEF_ID_ = DEF.ID_                                                                                             WHERE  (         1 = 1 and            SELF.PROC_INST_ID_ in               (                 ?               )                )       ) RES          order by RES.ID_ asc     LIMIT ? OFFSET ?
   275 ### Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
   276                 at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
   277                 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
   278                 at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
   279                 at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.selectList(DbSqlSession.java:97)
   280                 at org.camunda.bpm.engine.impl.db.entitymanager.DbEntityManager.selectListWithRawParameter(DbEntityManager.java:181)
```

**Comment by dostalradim** [comment]
I am trying to set parameter DB_VALIDATE_ON_BORROW to true with SELECT 1 query.

**Comment by MaxTru** [comment]
Hi,

this is not an issue in the Camunda Modeler. 
For Camunda Process Engine related question or bugs please head to the Camunda Forum https://forum.camunda.org/.
