### ISSUE TITLE
cannot start camunda-modeler.exe

### ISSUE THREAD

**Issue by icaha** [camunda/camunda-modeler#208]
Until last friday, I have used this program(camunda-modeler-win32-x64.zip) with no problem.
But today morning, when I run camunda-modeler.exe on my PC (windows 7 64bit), the error message dialog pops up. (See below)
Why??

Uncaught Exception:
SyntaxError: Unexpected token }
at Object.parse (native)
at Config.loadSync (D:\camunda-modeler\resources\app.asar\app\Config.js:27:23)
at Function.load (D:\camunda-modeler\resources\app.asar\app\Config.js:94:10)
at Object.<anonymous> (D:\camunda-modeler\resources\app.asar\app\index.js:25:21)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Object.<anonymous> (D:\camunda-modeler\resources\atom.asar\browser\lib\init.js:125:10)
at Object.<anonymous> (D:\camunda-modeler\resources\atom.asar\browser\lib\init.js:127:4)

**Comment by nikku** [comment]
Which version of the Modeler are you using (check the `version` file in the distribution).

**Comment by ricardomatias** [comment]
I'm fixing this now, it's related to the changes made for the workspace feature. It's a nightly release problem.

**Comment by ricardomatias** [comment]
Fixed with f54953d.

**Comment by icaha** [comment]
Nightly build of March 15th starts successfully.
Thank you!
