### ISSUE TITLE
Decide on the shared clipboard

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2124]
__What should we do?__

In Camunda Modeler, the clipboard is shared between BPMN diagrams. This means that you can copy an element from `diagram_1.bpmn` and paste it to `diagram_2.bpmn`. 

However, you cannot easily copy an element with Camunda properties to a Zeebe diagram (and Zeebe properties to a Camunda diagram respectively) as this leads to errors. For example, `zeebe:FormDefinition` does not have any execution meaning within Camunda Workflow Engine. Because of that, we've decided to not include the shared clipboard in https://github.com/camunda/camunda-modeler/pull/2107.

I can see three different options how to solve this problem:

- disable shared clipboard (as in https://github.com/camunda/camunda-modeler/pull/2107)
- allow to copy and paste elements but ignore process engine-specific properties (this requires additional work)
- try to convert the elements (rather infeasible)

__Why should we do it?__

Let's make an informed decision to replace the temporary solution or leave it as it is.

----

Child of https://github.com/bpmn-io/internal-docs/issues/614

**Comment by nikku** [comment]
I personally favor option two. The other options look rather odd.

Could you elaborate how that causes errors / harm? Would love to get a better understanding.

**Comment by barmac** [comment]
The element is not pasted and en error is logged:

```
[diagram_1.bpmn] unknown type <zeebe:FormDefinition>
    at Registry.mapTypes (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:525:11)
    at Registry.getEffectiveDescriptor (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:550:8)
    at BpmnModdle.Moddle.getType (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:775:32)
    at BpmnModdle.Moddle.create (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:743:19)
    at BpmnFactory.create (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/modeling/BpmnFactory.js:68:29)
    at ModdleCopy.copyProperty (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/copy-paste/ModdleCopy.js:241:40)
    at eval (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/copy-paste/ModdleCopy.js:222:29)
    at eval (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:221:14)
    at forEach (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:181:16)
    at reduce (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:220:3) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
unknown type <zeebe:FormDefinition>
    at Registry.mapTypes (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:525:11)
    at Registry.getEffectiveDescriptor (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:550:8)
    at BpmnModdle.Moddle.getType (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:775:32)
    at BpmnModdle.Moddle.create (webpack-internal:///../../camunda-bpmn-js/node_modules/moddle/dist/index.esm.js:743:19)
    at BpmnFactory.create (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/modeling/BpmnFactory.js:68:29)
    at ModdleCopy.copyProperty (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/copy-paste/ModdleCopy.js:241:40)
    at eval (webpack-internal:///../../camunda-bpmn-js/node_modules/bpmn-js/lib/features/copy-paste/ModdleCopy.js:222:29)
    at eval (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:221:14)
    at forEach (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:181:16)
    at reduce (webpack-internal:///../../camunda-bpmn-js/node_modules/min-dash/dist/index.esm.js:220:3) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

**Comment by nikku** [comment]
Pretty cool. This means the only thing we need is to check whether we "know such elements" and ignore the copy process all together?

**Comment by barmac** [comment]
That's what I would test first. So sth like:
```javascript
if (!moddle.canCreate(propertyOrElement)) {
  return false;
}
```

**Comment by falko** [comment]
This could have been a workaround for #2283

**Comment by nikku** [comment]
Strategy taken is described in the issue as:

> allow to copy and paste elements but ignore process engine-specific properties (this requires additional work)

Will be shipped via camunda-bpmn-js update (https://github.com/camunda/camunda-bpmn-js/pull/437).

**Comment by nikku** [comment]
Settled on native OS clipboard, cf. https://github.com/camunda/camunda-modeler/pull/5539.

Copy and paste is only enabled on BPMN editors, would need to be enabled for [forms](https://github.com/camunda/camunda-modeler/issues/5417) and DMN, too.
