### ISSUE TITLE
Templates with incompatible Schema version still show up in the Catalog Modal

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2162]
__Describe the Bug__

Given the following example templates

```json
[
  {
    "$schema": "https://unpkg.com/browse/@camunda/element-templates-json-schema@0.3.0/resources/schema.json",
    "name": "Simple Template",
    "id": "custom.example.template",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": []
  },
  {
    "$schema": "https://unpkg.com/browse/@camunda/element-templates-json-schema@0.2.0/resources/schema.json",
    "name": "Simple Template2",
    "id": "custom.example.template2",
    "appliesTo": [
      "bpmn:ServiceTask"
    ],
    "properties": []
  }
]
```

both templates are still shown up in the Catalog Modal, although the first one is marked as incompatible.

![image](https://user-images.githubusercontent.com/9433996/111622942-1509e880-87ea-11eb-9883-55f1be629099.png)

```text
[diagram_1.bpmn] template(id: <custom.example.template>, name: <Simple Template>): unsupported element template schema version <0.3.0>. Your installation only supports up to version <0.2.0>. Please update your installation
    at e.exports._logError (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:357:12)
    at _logError (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:127:18)
    at _validateTemplate (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:79:19)
    at Array.forEach (<anonymous>)
    at forEach (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/Validator.js:64:16)
    at addAll (webpack:///node_modules/bpmn-js-properties-panel/lib/provider/camunda/element-templates/ElementTemplatesLoader.js:74:34)
    at setTemplates (webpack:///src/app/tabs/bpmn/BpmnEditor.js:205:20)
    at async file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:65:113728 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

Furthermore, when applying this template, there is a "Missing Template" error showing up.

![image](https://user-images.githubusercontent.com/9433996/111623091-379c0180-87ea-11eb-8064-49c6ffb63c66.png)

__Steps to Reproduce__

1. Create a service task
2. Open the Catalog Modal
3. Choose the Template with the incompatible Schema version
4. See the Missing Template error

__Expected Behavior__

Element templates with incompatible schema version do not show up in the Catalog Modal

__Environment__

- OS: macOS@10.15.7
- Camunda Modeler Version: current nightly `20210317`

**Comment by pinussilvestrus** [comment]
This could be related to https://github.com/camunda/camunda-modeler/issues/2110, which we already fixed on `master`, but didn't merged to `develop` yet.

**Comment by pinussilvestrus** [comment]
I merged `master` into `develop` which fixes the problem.
