### ISSUE TITLE
Migrate to new Zeebe Endpoint APIs (for deploy and run)

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2169]
__Is your feature request related to a problem? Please describe.__

The Camunda Modeler (Zeebe Tabs) offers the option to "deploy" or "run" (start instance) of a Zeebe process using the "Deploy and run" modal menues. 

With the 1.0.0 the Zeebe Broker APIs will change (in particular: `workflow` will be renamed to `process`). Hence the "Deploy and run" feature will not work anymore. (This can be tested using the [`1.0.0-alpha3` release of Zeebe Broker or later](https://github.com/camunda-cloud/zeebe/releases)).

__Describe the solution you'd like__

* Update to a later version of https://github.com/camunda-community-hub/zeebe-client-node-js which supports the new `1.0.0` broker API endpoints. 
* Release this change on 11.05.2021 (together with Zeebe 1.0.0 stable).
* Document that Camunda-Modeler v4.8.0 (tbd) supports only Zeebe 1.0.0+ for deploy and run features

__Describe alternatives you've considered__

n/a

__Additional context__

cc. @menski 
cc. @jwulf. @jwulf , as far as I understood the to be used zeebe-node-js version would be based on the JS (not the native gRPC) implementation right? Because otherwise, we would run into problems (because of Electron incompatability, we so far were not able to use the native gRPC implementation)

**Comment by barmac** [comment]
> Because otherwise, we would run into problems (because of Electron incompatability, we so far were not able to use the native gRPC implementation)

We are actually using the native gRPC implementation in both the nightly and upcoming 4.7 release.

**Comment by MaxTru** [comment]
Thanks @barmac , even better then :-) Thanks for clarifying :+1:

**Comment by barmac** [comment]
Happy to help :)

**Comment by barmac** [comment]
I've just tested Zeebe 1.0.0-alpha.3 together with zeebe-node@1.0.0-alpha.3 and was able to deploy and run without trouble.

**Comment by barmac** [comment]
I've tested zeebe-node@1.0.0-alpha.3 with Zeebe 0.26.0. The deployment fails and an empty error is logged to the client. In the backend, the error message looks as follows:

```
ERROR app:zeebe-api Failed to deploy with config (secrets omitted): {
  filePath: '/Users/maciej/Desktop/diagram_1.bpmn',
  name: 'diagram_1',
  endpoint: { type: 'selfHosted', url: '0.0.0.0:26500' }
} Error: 12 UNIMPLEMENTED: Method not found: gateway_protocol.Gateway/DeployProcess
    at Object.exports.createStatusError (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.onReceiveStatus (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/zeebe-node/dist/lib/GrpcClient.js:145:36)
    at InterceptingListener._callNext (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/maciej/workspace/bpmn-io/camunda-modeler/app/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'Method not found: gateway_protocol.Gateway/DeployProcess'
}
```

**Comment by nikku** [comment]
Expected, as this is a breaking change (i believe `workflow` got renamed to `process`).

We could consider to catch these incompatibilities. As we've discussed we'll only support Camunda Cloud / Zeebe 1.0 and upwards in the Camunda Modeler.
