### ISSUE TITLE
Error raised when copying Service Task with "Empty" Error Event Definition

### ISSUE THREAD

**Issue by pinussilvestrus** [camunda/camunda-modeler#2196]
__Describe the Bug__

An error is raised in the Log when copying a Service Task, containing an error event definition _without referenced error_.

<img width="1552" alt="Bildschirmfoto 2021-04-08 um 14 19 58" src="https://user-images.githubusercontent.com/9433996/114025555-85e67280-9875-11eb-978c-31ec15b83e3e.png">

```text
Cannot read property 'id' of undefined
    at id (webpack:///node_modules/camunda-bpmn-moddle/lib/CopyPasteRootElementBehavior.js:33:63)
    at file:///Volumes/Camunda%20Modeler%204.7.0-rc.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/7.7.js:1:172358
    at Array.forEach (<anonymous>)
    at file:///Volumes/Camunda%20Modeler%204.7.0-rc.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/7.7.js:1:172335
    at file:///Volumes/Camunda%20Modeler%204.7.0-rc.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/2.2.js:1:49241
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:371:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:352:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:313:23)
    at file:///Volumes/Camunda%20Modeler%204.7.0-rc.0/Camunda%20Modeler.app/Contents/Resources/app.asar/public/3.3.js:1:88757
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

__Steps to Reproduce__

Given this example diagram

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_00xn31x" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.7.0-rc.0" modeler:executionPlatform="Camunda Platform" modeler:executionPlatformVersion="7.14.0">
  <bpmn:process id="Process_1ydm1hc" isExecutable="true">
    <bpmn:serviceTask id="Activity_07pclkm" camunda:type="external" camunda:topic="foo">
      <bpmn:extensionElements>
        <camunda:errorEventDefinition id="ErrorEventDefinition_1eoviwj" />
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1ydm1hc">
      <bpmndi:BPMNShape id="Activity_14qdgms_di" bpmnElement="Activity_07pclkm">
        <dc:Bounds x="160" y="77" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

1. Copy Service Task
2. Paste it somewhere
3. Error is appearing, pasting is not successful

__Expected Behavior__

Copy & Paste succeed without error.

__Environment__

- OS: MacOS 10.15
- Camunda Modeler Version: v4.7.0-rc.0

**Comment by philippfromme** [comment]
Can reproduce. Good catch!

**Comment by MaxTru** [comment]
Closed by https://github.com/camunda/camunda-modeler/pull/2200
