### ISSUE TITLE
Copy Pasting an element which has a element template, referring to an error, creates duplicate ID error

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-modeler#2202]
__Is your feature request related to a problem? Please describe.__

Copy Pasting an element which has a element template applied, which includes a bpmn:Error, creates duplicate ID error.
![copyPasteError](https://user-images.githubusercontent.com/42800119/114156093-7ec96e00-9922-11eb-963f-408c51ef37c7.gif)

__Describe the solution you'd like__

Copy Paste should work

__Describe alternatives you've considered__

1. Set up the following element template
```json
[
        {
  "name": "My super awesome UI Path template",
  "description": "",
  "id": "7aedee1c-d22d-4e3b-b9b4-093fcd1cedad",
  "appliesTo": [
    "bpmn:ServiceTask"
  ],
  "properties": [
    {
      "type": "Hidden",
      "value": "This is so awesome",
      "binding": {
        "type": "property",
        "name": "name"
      }
    },
    {
      "label": "UiPath Package Name",
      "type": "String",
      "value": "",
      "editable": false,
      "binding": {
        "type": "camunda:property",
        "name": "bot"
      }
    },
    {
      "type": "Hidden",
      "value": "external",
      "binding": {
        "type": "property",
        "name": "camunda:type"
      }
    },
    {
      "type": "Hidden",
      "value": "uipath",
      "binding": {
        "type": "property",
        "name": "camunda:topic"
      }
    },
    {
      "type": "Hidden",
      "value": "true",
      "binding": {
        "type": "property",
        "name": "camunda:asyncAfter"
      }
    },
    {
      "label": "a",
      "value": "${a}",
      "description": "a",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "a"
      }
    },
    {
      "label": "c",
      "value": "${c}",
      "description": "casdf",
      "binding": {
        "type": "camunda:inputParameter",
        "name": "c"
      }
    },
    {
      "label": "b",
      "value": "b",
      "description": "b",
      "binding": {
        "type": "camunda:outputParameter",
        "source": "${b}"
      }
    },
    {
      "label": "new",
      "value": "blub",
      "binding": {
        "type": "camunda:errorEventDefinition",
        "errorRef": "81671d66-31a9-4f9f-b2dc-dc42baf0f708"
      }
    }
  ],
  "scopes": [
    {
      "type": "bpmn:Error",
      "id": "81671d66-31a9-4f9f-b2dc-dc42baf0f708",
      "properties": [
        {
          "label": "Error Code",
          "type": "Hidden",
          "value": "error",
          "binding": {
            "type": "property",
            "name": "errorCode"
          }
        },
        {
          "label": "Error Message",
          "type": "Hidden",
          "value": "",
          "binding": {
            "type": "property",
            "name": "camunda:errorMessage"
          }
        },
        {
          "label": "Error Name",
          "type": "Hidden",
          "value": "new",
          "binding": {
            "type": "property",
            "name": "name"
          }
        }
      ]
    }
  ]
}
]
```
2. Apply to a service task
3. Copy paste the service task
4. Error:
```
[diagram_3.bpmn] Cannot read property 'id' of undefined
    at id (webpack:///node_modules/camunda-bpmn-moddle/lib/CopyPasteRootElementBehavior.js:33:63)
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/7.7.js:1:171842
    at Array.forEach (<anonymous>)
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/7.7.js:1:171821
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:18116
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:49241
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:371:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:352:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:313:23)
    at fire (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:356:28)
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:90914
    at fn (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:377:4)
    at _atomicDo (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:408:7)
    at _internalExecute (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:153:7)
    at execute (webpack:///node_modules/diagram-js/lib/features/modeling/Modeling.js:291:21)
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:99810
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at elements (webpack:///node_modules/diagram-js/lib/features/modeling/cmd/CreateElementsHandler.js:68:10)
    at preExecute (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:401:14)
    at _internalExecute (webpack:///node_modules/diagram-js/lib/command/CommandStack.js:153:7)
    at execute (webpack:///node_modules/diagram-js/lib/features/modeling/Modeling.js:317:21)
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:34487
    at file:///home/maxtru/Dokumente/99_tmp/4.7_IntegrationTest/camunda-modeler-4.7.0-rc.0-linux-x64/resources/app.asar/public/2.2.js:1:49241
    at listener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:371:33)
    at _invokeListener (webpack:///node_modules/diagram-js/lib/core/EventBus.js:352:23)
    at _invokeListeners (webpack:///node_modules/diagram-js/lib/core/EventBus.js:313:23)
    at fire (webpack:///node_modules/diagram-js/lib/features/dragging/Dragging.js:169:20)
    at fire (webpack:///node_modules/diagram-js/lib/features/dragging/Dragging.js:265:20)
    at end (webpack:///node_modules/diagram-js/lib/features/dragging/Dragging.js:314:4)
    at apply (webpack:///node_modules/@sentry/browser/esm/helpers.js:71:22) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
[...]
```

__Additional context__

Discovered as part of https://github.com/camunda/camunda-modeler/issues/2157 integration testing

**Comment by pinussilvestrus** [comment]
Can you double-check whether this happens on the current `master` as well?

Might be addressed by https://github.com/camunda/camunda-modeler/issues/2196

**Comment by MaxTru** [comment]
Will do

**Comment by MaxTru** [comment]
This was resolved! :tada: 

But related this, I found: https://github.com/camunda/camunda-modeler/issues/2203
