### ISSUE TITLE
Cannot read property open of undefined when toggling properties panel for the first time

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#2252]
__Describe the Bug__

On a clean installation of Camunda Modeler, when I click "Toggle properties panel", an error appears:

```
2021-05-10T11:38:06.814Z  ERROR client Cannot read property 'open' of undefined
    at open (webpack:///src/app/tabs/dmn/DmnEditor.js:614:39)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:259:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1719:15)
    at fn (webpack:///src/app/App.js:2244:19)
    at file:///Applications/Camunda%20Modeler%204.7.app/Contents/Resources/app.asar/public/bundle.js:65:127778
    at exec (webpack:///src/app/AppParent.js:76:11)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2469:16)
```

__Steps to Reproduce__

1. Remove config.json
2. Open Camunda Modeler
3. Click "Toggle properties panel" in the menu

https://user-images.githubusercontent.com/28307541/117653863-40c7a000-b195-11eb-9700-2a09dba82722.mov

__Expected Behavior__

No errors.

__Environment__

- OS: macOS
- Camunda Modeler Version: 4.7, 4.8
- Installed plug-ins: [...]

**Comment by barmac** [comment]
This is *not* a regression of 4.8.0.

**Comment by philippfromme** [comment]
Will investigate as it appears to be a quick fix.

**Comment by barmac** [comment]
This is not only in DMN, but also BPMN tab.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/pull/2255
