### ISSUE TITLE
Development Setup Broken on Windows

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler#2269]
__Describe the Bug__

Running `npm i` fails at the `postinstall` step which runs `electron-builder install-app-deps`. I've tried with a fresh installation of Windows - no success.

This is likely a result of https://github.com/camunda/camunda-modeler/issues/2114 which introduced the `postinstall` script.

Log:

```bash
4598 verbose stack Error: grpc@1.24.7 install: `node-pre-gyp install --fallback-to-build --library=static_library`
4598 verbose stack Exit status 1
4598 verbose stack     at EventEmitter.<anonymous> (C:\Users\PhilippFromme\AppData\Roaming\nvm\v14.17.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
4598 verbose stack     at EventEmitter.emit (events.js:376:20)
4598 verbose stack     at ChildProcess.<anonymous> (C:\Users\PhilippFromme\AppData\Roaming\nvm\v14.17.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4598 verbose stack     at ChildProcess.emit (events.js:376:20)
4598 verbose stack     at maybeClose (internal/child_process.js:1055:16)
4598 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
4599 verbose pkgid grpc@1.24.7
4600 verbose cwd C:\workspace\camunda\camunda-modeler\app
4601 verbose Windows_NT 10.0.19041
4602 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PhilippFromme\\AppData\\Roaming\\nvm\\v14.17.0\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999"
4603 verbose node v14.17.0
4604 verbose npm  v6.14.13
4605 error code ELIFECYCLE
4606 error errno 1
4607 error grpc@1.24.7 install: `node-pre-gyp install --fallback-to-build --library=static_library`
4607 error Exit status 1
4608 error Failed at the grpc@1.24.7 install script.
4608 error This is probably not a problem with npm. There is likely additional logging output above.
4609 verbose exit [ 1, true ]
```

__Tasks__

* [ ] Clearly document resolution
* [ ] Document resolution, if applicable amend contribution guidelines to cover the required setup steps

__Environment__

- OS: Windows 10
- Camunda Modeler Version: 4.8.1

**Comment by barmac** [comment]
![IMG_20210517_103951](https://user-images.githubusercontent.com/28307541/118459773-5a6c6880-b6fc-11eb-9fe8-ec8ad6010c5f.jpg)

I was able to reproduce it.

**Comment by barmac** [comment]
Debugging output:

[output.txt](https://github.com/camunda/camunda-modeler/files/6492519/output.txt)

**Comment by barmac** [comment]
It seems that missing Python installation might be the root cause:

```
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
```

**Comment by barmac** [comment]
After Python installation:

[output.txt](https://github.com/camunda/camunda-modeler/files/6492629/output.txt)

**Comment by nikku** [comment]
On Windows you need to take [dedicated steps](https://github.com/nodejs/node-gyp#on-windows) to get node-gyp / native compilation to work.

**Comment by nikku** [comment]
Installing Python (and Visual Studio Express) are two steps on the checklist.

**Comment by nikku** [comment]
For what it is worth, we should mention whatever we find out in the Camunda Modeler contributing guidelines, too. Will surely bite many of the potential Windows using Camunda Modeler contributors out there.

**Comment by barmac** [comment]
![IMG_20210517_120411](https://user-images.githubusercontent.com/28307541/118471627-3f9ff100-b708-11eb-989c-4154f62ec069.jpg)

It works on my Windows machine.

**Comment by barmac** [comment]
What I did:

1. Install `nvm-windows`
2. Install Node.js 14.17.0 with `nvm-windows`
3. Install Python 3.9.5 from https://www.python.org/
4. Install Visual Studio 2019 Community from https://visualstudio.microsoft.com/; components:
  * Node.js
  * Python
  * C++
  * selected also additional C++ components from the list

@philippfromme How does your setup differ?

**Comment by barmac** [comment]
System info from Visual Studio:

```
Microsoft Visual Studio Community 2019
Version 16.9.5
VisualStudio.16.Release/16.9.5+31229.75
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA549
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.21111.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21111.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Profiling support   16.9.21111.1
Profiling support for Python projects.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

**Comment by nikku** [comment]
This likely does it. Windows users simply need to [follow the documented steps](https://github.com/camunda/camunda-modeler/issues/2269#issuecomment-842169150) to get compilation / `node-gyp` to work.

**Comment by nikku** [comment]
Assigned to @philippfromme to validate and fix (documentation wise).

**Comment by philippfromme** [comment]
I was missing the C++ build tools. Such an easy fix. Thanks for your effort, @barmac. 🏅 I will update the documentation. Follow-up issue: https://github.com/camunda/camunda-modeler/issues/2274
