### ISSUE TITLE
'mv' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by wsteven24** [camunda/camunda-modeler#2821]
I'm getting this error when running "npm run build":

'mv' is not recognized as an internal or external command,
operable program or batch file.
ERROR: "client:build" exited with 1.

**Comment by pinussilvestrus** [comment]
Please provide the necessary information [by using our issue template](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.md). Especially your environment (os) would be really helpful to understand your issue.

**Comment by Skaiir** [comment]
This is due to the postbuild step in `client/package.json` using `mv` which isn't cross platform and won't work on powershell and cmd. 

@wsteven24 A workaround would be to use git bash instead. We don't support the basic windows terminals explicitly but are slowly making things more and more cross platform. Ultimately the best would be for it to work everywhere :D.

This item is something we can have a look at in the future during spring cleaning.

**Comment by wsteven24** [comment]
Thank you @Skaiir, I tried on git bash and got a different error, can you provide some hints? I'm newbie :

```
wsochoa@mlan11214p446 MINGW64 /c/Git/Camunda-modeler (master)
$ npm run build

> camunda-modeler-builder@0.0.0 build
> run-s client:build "build:distro -- {@}" "build:test-distro -- {@}" --


> camunda-modeler-builder@0.0.0 client:build
> (cd client && npm run build)


> camunda-modeler-client@4.12.0 build
> cross-env NODE_ENV=production webpack

Hash: 361d6357d422e67e03a4
Version: webpack 4.30.0
Time: 24825ms
Built at: 03/22/2022 3:25:42 PM
                         Asset      Size  Chunks                    Chunk Names
                        0.0.js   193 KiB       0  [emitted]
                    0.0.js.map   745 KiB       0  [emitted]
                        1.1.js   127 KiB       1  [emitted]
                    1.1.js.map   470 KiB       1  [emitted]
                      10.10.js   134 KiB      10  [emitted]
                  10.10.js.map   439 KiB      10  [emitted]
                      11.11.js  33.1 KiB      11  [emitted]
                  11.11.js.map   110 KiB      11  [emitted]
                      12.12.js  27.7 KiB      12  [emitted]
                  12.12.js.map  99.2 KiB      12  [emitted]
                        2.2.js  40.6 KiB       2  [emitted]
                    2.2.js.map   227 KiB       2  [emitted]
                        3.3.js   610 KiB       3  [emitted]  [big]
                    3.3.js.map  2.07 MiB       3  [emitted]
                        5.5.js   535 KiB       5  [emitted]  [big]
                    5.5.js.map  1.92 MiB       5  [emitted]
                        6.6.js   185 KiB       6  [emitted]
                    6.6.js.map   745 KiB       6  [emitted]
                        7.7.js   802 KiB       7  [emitted]  [big]
                    7.7.js.map  2.76 MiB       7  [emitted]
                        8.8.js   698 KiB       8  [emitted]  [big]
                    8.8.js.map  1.96 MiB       8  [emitted]
                        9.9.js  57.3 KiB       9  [emitted]
                    9.9.js.map   197 KiB       9  [emitted]
                     bundle.js   853 KiB       4  [emitted]  [big]  bundle
                 bundle.js.map     3 MiB       4  [emitted]         bundle
                    index.html   1.5 KiB          [emitted]
static/media/app.0796b531.woff  6.57 KiB          [emitted]
 static/media/app.246f1365.ttf  11.4 KiB          [emitted]
 static/media/app.a62c34b3.svg   9.7 KiB          [emitted]
 static/media/app.c8fd546b.eot  11.5 KiB          [emitted]
static/media/bpmn.08b5f281.eot  46.6 KiB          [emitted]
static/media/bpmn.1381b44e.svg   130 KiB          [emitted]
static/media/cmmn.9f6d95c9.svg  23.5 KiB          [emitted]
static/media/cmmn.b3c27689.eot  19.7 KiB          [emitted]
 static/media/dmn.77b9ea7b.svg  15.1 KiB          [emitted]
 static/media/dmn.fb276b69.eot  14.8 KiB          [emitted]
Entrypoint bundle [big] = bundle.js bundle.js.map
  [2] ./src/shared/ui/index.js + 21 modules 34 KiB {4} [built]
      | ./src/shared/ui/index.js 632 bytes [built]
      | ./src/shared/ui/Button.js 1.08 KiB [built]
      | ./src/shared/ui/DropdownButton.js 4.42 KiB [built]
      | ./src/shared/ui/icon/index.js 424 bytes [built]
      | ./src/shared/ui/modal/index.js 426 bytes [built]
      | ./src/shared/ui/overlay/index.js 472 bytes [built]
      | ./src/shared/ui/form/index.js 580 bytes [built]
      | ./src/shared/ui/icon/Icon.js 657 bytes [built]
      | ./src/shared/ui/modal/Modal.js 3.39 KiB [built]
      | ./src/shared/ui/overlay/Overlay.js 4.15 KiB [built]
      | ./src/shared/ui/overlay/OverlayDropdown.js 2.31 KiB [built]
      | ./src/shared/ui/form/CheckBox.js 1.38 KiB [built]
      | ./src/shared/ui/form/TextInput.js 1.67 KiB [built]
      | ./src/shared/ui/form/Radio.js 2.2 KiB [built]
      | ./src/shared/ui/form/FileInput.js 3.11 KiB [built]
      |     + 7 hidden modules
  [5] ./src/util/Flags.js 1.45 KiB {4} [built]
 [10] ./src/app/slot-fill/index.js + 3 modules 4.68 KiB {4} [built]
      | ./src/app/slot-fill/index.js 516 bytes [built]
      | ./src/app/slot-fill/Fill.js 1.48 KiB [built]
      | ./src/app/slot-fill/SlotFillRoot.js 2.15 KiB [built]
      | ./src/app/slot-fill/FillContext.js 554 bytes [built]
 [13] ./src/util/index.js + 8 modules 12 KiB {4} [built]
      | ./src/util/index.js 632 bytes [built]
      | ./src/util/generate-id.js 501 bytes [built]
      | ./src/util/throttle.js 1000 bytes [built]
      | ./src/util/metrics/index.js 1.17 KiB [built]
      | ./src/util/metrics/processVariables.js 970 bytes [built]
      | ./src/util/metrics/userTasks.js 2.83 KiB [built]
      | ./src/util/metrics/serviceTasks.js 2.37 KiB [built]
      | ./src/util/extensionElementsHelpers.js 1.09 KiB [built]
      | ./src/util/formHelpers.js 1.42 KiB [built]
 [16] ./src/util/Metadata.js 1.07 KiB {4} [built]
 [27] ./src/app/primitives/index.js + 7 modules 17 KiB {4} [built]
      | ./src/app/primitives/index.js 576 bytes [built]
      | ./src/app/primitives/Loader.js 632 bytes [built]
      | ./src/app/primitives/TabLinks.js 4.08 KiB [built]
      | ./src/app/primitives/TabContainer.js 648 bytes [built]
      | ./src/app/primitives/Tab.js 630 bytes [built]
      | ./src/app/util/scroller.js 777 bytes [built]
      | ./src/app/util/dragger.js 658 bytes [built]
      |     + 1 hidden module
 [36] ./src/shared/ui/modal/KeyboardInteractionTrap.js 2.18 KiB {4} [built]
 [82] ./src/app/cached/index.js + 5 modules 7.04 KiB {4} [built]
      | ./src/app/cached/index.js 664 bytes [built]
      | ./src/app/cached/Cache.js 931 bytes [built]
      | ./src/app/cached/CacheContext.js 522 bytes [built]
      | ./src/app/cached/WithCache.js 1.41 KiB [built]
      | ./src/app/cached/WithCachedState.js 2.97 KiB [built]
      | ./src/app/cached/CachedComponent.js 604 bytes [built]
[101] ./src/app/tabs/util/namespace.js 2.72 KiB {4} [built]
[160] ./src/app/App.less 1.18 KiB {4} [built]
[164] ./src/app/tabs/bpmn/diagram.bpmn 1020 bytes {4} [built]
[196] multi ./src/index.js 28 bytes {4} [built]
[197] ./src/styles/style.less 1.19 KiB {4} [built]
[198] ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./src/styles/style.less 15 KiB {4} [built]
[357] ./src/index.js + 163 modules 583 KiB {4} [built]
      | ./src/index.js 1.82 KiB [built]
      | ./src/remote/index.js 1.18 KiB [built]
      | ./src/app/index.js 598 bytes [built]
      | ./src/remote/Config.js 3.22 KiB [built]
      | ./src/remote/Dialog.js 4.33 KiB [built]
      | ./src/remote/FileSystem.js 1.36 KiB [built]
      | ./src/remote/Log.js 541 bytes [built]
      | ./src/remote/Plugins.js 3.41 KiB [built]
      | ./src/remote/SystemClipboard.js 791 bytes [built]
      | ./src/remote/Workspace.js 684 bytes [built]
      | ./src/remote/ZeebeAPI.js 2.53 KiB [built]
      | ./src/app/App.js 44.2 KiB [built]
      | ./src/app/AppParent.js 11.5 KiB [built]
      | ./src/app/KeyboardBindings.js 10.2 KiB [built]
      | ./src/app/TabsProvider.js 12.9 KiB [built]
      |     + 149 hidden modules
    + 1118 hidden modules

WARNING in ./src/app/tabs/EngineProfile.js 236:17-33
"export 'DISABLE_PLATFORM' was not found in '../../util/Flags'
 @ ./src/app/tabs/cloud-bpmn/BpmnEditor.js
 @ ./src/app/tabs/cloud-bpmn/BpmnTab.js
 @ ./src/app/tabs/cloud-bpmn/index.js
 @ ./src/app/TabsProvider.js
 @ ./src/app/index.js
 @ ./src/index.js
 @ multi ./src/index.js

WARNING in ./src/app/tabs/EngineProfile.js 237:52-68
"export 'DISABLE_PLATFORM' was not found in '../../util/Flags'
 @ ./src/app/tabs/cloud-bpmn/BpmnEditor.js
 @ ./src/app/tabs/cloud-bpmn/BpmnTab.js
 @ ./src/app/tabs/cloud-bpmn/index.js
 @ ./src/app/TabsProvider.js
 @ ./src/app/index.js
 @ ./src/index.js
 @ multi ./src/index.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  3.3.js (610 KiB)
  bundle.js (853 KiB)
  5.5.js (535 KiB)
  7.7.js (802 KiB)
  8.8.js (698 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  bundle (853 KiB)
      bundle.js


> camunda-modeler-client@4.12.0 postbuild
> del-cli --force ../app/public && mv build ../app/public


> camunda-modeler-builder@0.0.0 build:distro
> node tasks/distro.js


Building camunda-modeler distro

---

  version: 4.12.0
  platforms: [current]
  publish: false

---

electron-builder -c.forceCodeSigning=false --publish=never -c.artifactName=${name}-${version}-${os}-${arch}.${ext} -c.dmg.artifactName=${name}-${version}-${os}.${ext} -c.nsis.artifactName=${name}-${version}-${os}-setup.${ext} -c.nsisWeb.artifactName=${name}-${version}-${os}-web-setup.${ext} -c.extraMetadata.SENTRY_DSN=null

  • electron-builder  version=22.10.5 os=10.0.19044
  • loaded configuration  file=C:\Git\Camunda-modeler\electron-builder.json
  • rebuilding native dependencies  dependencies=grpc@1.24.10 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path C:\Git\Camunda-modeler\app\node_modules\grpc
    npm ERR! command failed
    npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --library=static_library
    npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\wsochoa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Git\Camunda-modeler\app\node_modules\grpc\src\node\extension_binary\electron-v12.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Git\Camunda-modeler\app\node_modules\grpc\src\node\extension_binary\electron-v12.1-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v12.1 --python=C:\Users\wsochoa\Anaconda3\envs\ML\python.exe' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
    npm ERR! node-pre-gyp info using node@16.14.2 | win32 | x64
    npm ERR! node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.24.10/electron-v12.1-win32-x64-unknown.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.10/electron-v12.1-win32-x64-unknown.tar.gz
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.10 and electron@12.1.2 (electron-v12.1 ABI, unknown) (falling back to source compile with node-gyp)
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://node-precompiled-binaries.grpc.io/grpc/v1.24.10/electron-v12.1-win32-x64-unknown.tar.gz
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.14.2 | win32 | x64
    npm ERR! gyp info ok
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@9.0.0
    npm ERR! gyp info using node@16.14.2 | win32 | x64
    npm ERR! gyp info find Python using Python version 3.8.11 found at "C:\Users\wsochoa\Anaconda3\envs\ML\python.exe"
    npm ERR! gyp info find VS using VS2019 (16.11.31624.102) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Users\wsochoa\Anaconda3\envs\ML\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\Users\\wsochoa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Git\\Camunda-modeler\\app\\node_modules\\grpc\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\wsochoa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\wsochoa\\.electron-gyp\\12.1.2\\include\\node\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\wsochoa\\.electron-gyp\\12.1.2',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\wsochoa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\wsochoa\\\\.electron-gyp\\\\12.1.2\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Git\\Camunda-modeler\\app\\node_modules\\grpc',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'C:\\Git\\Camunda-modeler\\app\\node_modules\\grpc\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    npm ERR! gyp ERR! configure error
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\wsochoa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:261:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.19044
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wsochoa\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Git\\Camunda-modeler\\app\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v12.1-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Git\\Camunda-modeler\\app\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v12.1-win32-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v12.1" "--python=C:\\Users\\wsochoa\\Anaconda3\\envs\\ML\\python.exe"
    npm ERR! gyp ERR! cwd C:\Git\Camunda-modeler\app\node_modules\grpc
    npm ERR! gyp ERR! node -v v16.14.2
    npm ERR! gyp ERR! node-gyp -v v9.0.0
    npm ERR! gyp ERR! not ok
    npm ERR! node-pre-gyp ERR! build error
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\wsochoa\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Git\Camunda-modeler\app\node_modules\grpc\src\node\extension_binary\electron-v12.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Git\Camunda-modeler\app\node_modules\grpc\src\node\extension_binary\electron-v12.1-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v12.1 --python=C:\Users\wsochoa\Anaconda3\envs\ML\python.exe' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Git\camunda-modeler\app\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
    npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19044
    npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Git\\camunda-modeler\\app\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
    npm ERR! node-pre-gyp ERR! cwd C:\Git\Camunda-modeler\app\node_modules\grpc
    npm ERR! node-pre-gyp ERR! node -v v16.14.2
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
    npm ERR! node-pre-gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\wsochoa\AppData\Local\npm-cache\_logs\2022-03-22T14_25_47_450Z-debug-0.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\wsochoa\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js' rebuild grpc@1.24.10
                    workingDir=
  ⨯ C:\Git\camunda-modeler\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                     Error: C:\Git\camunda-modeler\node_modules\app-builder-lib\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                         at ChildProcess.<anonymous> (C:\Git\camunda-modeler\node_modules\app-builder-lib\node_modules\builder-util\src\util.ts:243:14)
                                                                                                                                                                         at Object.onceWrapper (node:events:646:26)
                                                                                                                                                                         at ChildProcess.emit (node:events:526:28)
                                                                                                                                                                         at maybeClose (node:internal/child_process:1092:16)
                                                                                                                                                                         at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
C:\Git\Camunda-modeler\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: electron-builder -c.forceCodeSigning=false --publish=never -c.artifactName=${name}-${version}-${os}-${arch}.${ext} -c.dmg.artifactName=${name}-${version}-${os}.${ext} -c.nsis.artifactName=${name}-${version}-${os}-setup.${ext} -c.nsisWeb.artifactName=${name}-${version}-${os}-web-setup.${ext} -c.extraMetadata.SENTRY_DSN=null
    at makeError (C:\Git\Camunda-modeler\node_modules\execa\index.js:174:9)
    at module.exports.sync (C:\Git\Camunda-modeler\node_modules\execa\index.js:338:15)
    at Object.<anonymous> (C:\Git\Camunda-modeler\tasks\distro.js:144:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'electron-builder -c.forceCodeSigning=false --publish=never -c.artifactName=${name}-${version}-${os}-${arch}.${ext} -c.dmg.artifactName=${name}-${version}-${os}.${ext} -c.nsis.artifactName=${name}-${version}-${os}-setup.${ext} -c.nsisWeb.artifactName=${name}-${version}-${os}-web-setup.${ext} -c.extraMetadata.SENTRY_DSN=null',
  timedOut: false
}
ERROR: "build:distro --" exited with 1.

```

**Comment by barmac** [comment]
Hi,

Try out the `develop` branch as the error you pasted originates in the `grpc` package on which we don't depend anymore.
