### ISSUE TITLE
Open BPMN diagram

### ISSUE THREAD

**Issue by JGCosta1** [camunda/camunda-modeler#2940]
__Describe the Bug__

The tab crashed due to unexpected error.

__Steps to Reproduce__

1. Open Camunda Moduler
2. BPMN diagram

__Expected Behavior__

[diagram_1.bpmn] No provider for "propertiesProvider"! (Resolving: alignToOrigin -> WysiwygPropertiesProvider -> propertiesProvider)
    at a (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:112:11)
    at error (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:98:14)
    at get (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:152:18)
    at file:///D:/CAMUNDA/Camunda%20Moduler/Camunda%20v5.0.0/resources/app.asar/public/4.4.js:1:35854
    at Array.map (<anonymous>)
    at map (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:170:30)
    at fnDef (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:185:14)
    at providers (webpack:///node_modules/bpmn-js/node_modules/didi/dist/index.esm.js:146:43)
    at file:///D:/CAMUNDA/Camunda%20Moduler/Camunda%20v5.0.0/resources/app.asar/public/4.4.js:1:60660
    at Array.forEach (<anonymous>)
    at forEach (webpack:///node_modules/bpmn-js/node_modules/diagram-js/lib/Diagram.js:49:13)
    at file:///D:/CAMUNDA/Camunda%20Moduler/Camunda%20v5.0.0/resources/app.asar/public/4.4.js:1:60814
    at options (webpack:///node_modules/bpmn-js/node_modules/diagram-js/lib/Diagram.js:139:56)
    at call (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:635:10)
    at _init (webpack:///node_modules/bpmn-js/lib/BaseViewer.js:65:7)
    at call (webpack:///node_modules/bpmn-js/lib/BaseModeler.js:22:13)
    at call (webpack:///node_modules/bpmn-js/lib/Modeler.js:136:14)
    at call (webpack:///node_modules/camunda-bpmn-js/lib/base/Modeler.js:25:14)
    at call (webpack:///node_modules/camunda-bpmn-js/lib/camunda-cloud/Modeler.js:50:14)
    at super (webpack:///src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js:36:4)
    at Function.createCachedState (webpack:///src/app/tabs/cloud-bpmn/BpmnEditor.js:802:20)
    at createCachedState (webpack:///src/app/cached/WithCachedState.js:55:19)
    at ui (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:132:169)
    at vf (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:167:148)
    at Og (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:180:29)
    at Tg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:232:21)
    at bi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:233:283)
    at ci (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:249:347)
    at Di (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack:///node_modules/react/cjs/react.production.min.js:13:223)
    at file:///D:/CAMUNDA/Camunda%20Moduler/Camunda%20v5.0.0/resources/app.asar/public/bundle.js:83:156316 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
@JGCosta1 This is clearly related to a plug-in you have installed:

```
[diagram_1.bpmn] No provider for "propertiesProvider"! (Resolving: alignToOrigin -> WysiwygPropertiesProvider -> propertiesProvider)
```

Please uninstall or fix that plug-in and you're good.

**Comment by JGCosta1** [comment]
But I haven´t any plugin installed ate this version of camunda.

I have plugin's in last version, but I don't know how this version show the plugins of last version.

I have the folder plugins empty.

Thanks
