### ISSUE TITLE
Camunda Modeler crashed loading a bpmn modeler

### ISSUE THREAD

**Issue by Phering** [camunda/camunda-modeler#3234]
### Describe the bug

[/<removed>/camunda/src/main/resources/META-INF/ApprovalMainProcess.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:193:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:1616732
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at setState (webpack://camunda-modeler-client/src/app/App.js:900:9)
    at setLintingState (webpack://camunda-modeler-client/src/app/App.js:877:9)
    at async file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:2820929 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]

### Steps to reproduce

1. Have a Camunda Modeler version 5.3 with plugins enabled on MacOs
2. Install new Camunda Modeler 5.4.1
3. Start modeler
4. Open diagram
5. Modeler crashes
6. follow advice form stacktrace: restart with plugins disabled
7. Modeler will start without error 
8. removed all existing plugins form plugins folder  (.../Application Support/camunda-modeler/plugins)
9. restart modeler with plugins enabled
10. open diagram: no crash
11. Added plugins one at a time to (new) plugins folder: /Applications/Camunda Modeler.app/Contents/MacOS/resources/plugins
12. after restart and open diagram: working normally
13. until linter plugin copied into plugins folder ==> crash 

### Expected behavior

Modeler won't crash or report when plugins are enabled
reactivate linter for bpmn models that work on C7

### Environment

- OS: MacOs 12.6
- Camunda Modeler Version: 5.4.1
- Camunda 7.1x
- Installed plug-ins: 
 - camunda-modeler-plugin-rename-technical-ids
 - camunda-modeler-property-info-plugin-master
 - camunda-transaction-boundaries-plugin
if have removed the following plugin that is causing the error
- camunda-modeler-linter-plugin

**Comment by nikku** [comment]
@Phering thanks for opening this issue.

We ship linter-plugin features with the core starting with Modeler v5.3+. Cf. https://github.com/camunda/camunda-modeler-linter-plugin. Unfortunately the plug-in system does not allow us to handle that issue gracefully, i.e. log a more meaningful error.

With Modeler v5.4 and beyond you'll be able to provide your lint rules via plug-ins and the core UI will handle validation + error display. If you critically rely on the linter plug-in (and the built-in lint rules) you may want to hold of from updating until v5.5 where the full integration is going to land.

**Comment by nikku** [comment]
For reference you find a summary of the improvements / changes we plan to ship at the core in https://github.com/camunda/camunda-modeler/issues/3145.

**Comment by nikku** [comment]
Closing as won't fix.
