### ISSUE TITLE
Cannot create a model anymore

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-modeler#3245]
### Describe the bug

I just downloaded the newest Modeler release (5.4.1) as dmg. I opened up the application and tried to create a new Camunda 8 BPMN file. This led to an exception being thrown. I have tried to repeat creating an new BPMN file without success. 

This image contains further information 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/30292227/196674868-0ba870cb-15f3-49b9-9cc1-5c30bc1234bf.png">

`[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:181:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:1616732
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at setState (webpack://camunda-modeler-client/src/app/App.js:900:9)
    at setLintingState (webpack://camunda-modeler-client/src/app/App.js:877:9)
    at async file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:2820929 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]`

I have got three plugins installed: 
<img width="227" alt="image" src="https://user-images.githubusercontent.com/30292227/196675215-dc70afe2-3983-44b7-80d1-5cf5c1665556.png">
Though I have no possibility to disable them through the Desktop Modeler. 

### Steps to reproduce

1. Install the Plugins for a future version of the Desktop Modeler
2. Update the Desktop Modeler to version (5.4.1) 
3. Try creating a new BPMN diagram 

### Expected behavior

Of course I would expect the Modeler to create a new bpmn file. In case this is due to a plugin my expectation is to see which one is responsible for this error. 

### Environment

- OS: MacOS 12.6
- Camunda Modeler Version: 5.4.1
- Execution Platform: Both are not working 
- Installed plug-ins: Token Simulation, Linting, Migration

**Comment by Hafflgav** [comment]
Update: It seems to be caused by the linting plugin

**Comment by barmac** [comment]
The linter plugin which you linked was replaced in Camunda Modeler 5.3+ with a built-in linter. You need to remove it if you want to use v5.4.1 of the app. If you want to use custom lint rules, check out this repo https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin
