### ISSUE TITLE
Cannot open files after having upgraded to 5.4.2

### ISSUE THREAD

**Issue by anaojedagit** [camunda/camunda-modeler#3253]
### Describe the bug

[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:193:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:1617571
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

### Steps to reproduce

1. Upgrade to 5.4.2
2. Try to open .bpmn file created for platform 7
3. Get error message

### Expected behavior

Ability to open files.

### Environment

- OS: MacOS 12.6
- Camunda Modeler Version: 5.4.2
- Execution Platform: Camunda Modeler
- Installed plug-ins: 

1. bpmn-js-embedded-comments-master
2. camunda-modeler-autosave-plugin
3. camunda-modeler-excel-import-plugin-main
4. camunda-modeler-linter-plugin-master
5. camunda-modeler-property-info-plugin-master
6. camunda-modeler-token-simulation-plugin
7. camunda-modeler-tooltip-plugin-0.0.9
8. cloud-connect-3
9. dmn-testing-plugin-master

### Additional context

Problem goes away after temporarily disabling plugins.

**Comment by anaojedagit** [comment]
Yes, the problem goes away with disabled plugins.

**Comment by codygulley** [comment]
I am also experiencing this issue . The only plugin I have installed is the [Camunda Linter Plugin](https://github.com/camunda/camunda-modeler-linter-plugin).   When I remove this plugin, the modeler loads appropriately. 

@marstamm  Any help with getting this plugin to work would be greatly appreciated.  As this is a plugin provided in the Camunda Github and specifically linked in the [Camunda Modeler Plugins](https://github.com/camunda/camunda-modeler-plugins) is this something that the Camunda team can please update?
