### ISSUE TITLE
Validation of C7 diagram fails with `Error: showLintError is not a registered action`

### ISSUE THREAD

**Issue by strangelookingnerd** [camunda/camunda-modeler#3329]
__Describe the issue__

So I build the [camunda-modeler-custom-linter-rules plugin](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin) project template (without any changes!) and added it to my modeler. I get the following error when clicking on the error in the Linter Tab in a C7 diagram:

```
showLintError is not a registered action
    at Ba (webpack://camunda-modeler-client/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:259:9)
    at error (webpack://camunda-modeler-client/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:169:10)
    at trigger (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:723:40)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack://camunda-modeler-client/src/app/App.js:1831:15)
    at file:///MY_DISK/camunda-modeler-win/resources/app.asar/public/bundle.js:2:2883152
    at file:///MY_DISK/camunda-modeler-win/resources/app.asar/public/72.js:1:3411
    at file:///MY_DISK/camunda-modeler-win/resources/app.asar/public/490.js:1:8466
    at apply (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:14:427) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin/issues/new#) [ info ]
```

__Steps to reproduce__

![capture 0x2C7g_optimized](https://user-images.githubusercontent.com/58601/205354943-d3707095-412d-4961-be7d-7ea7d01edea7.gif)

__Expected Behavior__

Linting works in C7 diagrams, too.

__Environment__

Camunda Modeler 5.5.1 / also nightly.
C7 diagram modeling.

**Comment by strangelookingnerd** [comment]
Same error with the nightly for me:

```
showLintError is not a registered action
    at us (webpack://camunda-modeler-client/node_modules/bpmn-js/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:259:9)
    at error (webpack://camunda-modeler-client/node_modules/bpmn-js/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:169:10)
    at trigger (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:723:40)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack://camunda-modeler-client/src/app/App.js:1831:15)
    at file:///MY_DISK/camunda-modeler/resources/app.asar/public/bundle.js:2:2641508
    at file:///MY_DISK/camunda-modeler/resources/app.asar/public/72.js:1:3411
    at file:///MY_DISK/camunda-modeler/resources/app.asar/public/900.js:1:9351
    at apply (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:14:427) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
```

**Comment by nikku** [comment]
We'd need to fix this / address this in C7.

**Comment by nikku** [comment]
Thanks for taking your time to report all these glitches.
