### ISSUE TITLE
Modeler crashing due to plugins

### ISSUE THREAD

**Issue by talesmp** [camunda/camunda-modeler#3401]
### Describe the bug

The Modeler crashes as soon as you open, reporting a plugin error.

Current plugins:
- BPMN Driven Testing
- BPMN Linter
- Rename Technical IDs
- bpmn-js Token Simulation
- Tooltip Plugin 

```
[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:193:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:946340
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at setState (webpack://camunda-modeler-client/src/app/App.js:900:9)
    at setLintingState (webpack://camunda-modeler-client/src/app/App.js:877:9)
    at async file:///Applications/Camunda%20Modeler.app/Contents/Resources/app.asar/public/bundle.js:2:2643974 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
```

### Steps to reproduce

Just have those plugins in you folder and try to open the Modeler. It crashes immediately.

### Expected behavior

It should open the Modeler, not crash.

### Environment

- OS: MacOS 12.6.2
- Camunda Modeler Version: 5.7.0
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: 
   - BPMN Driven Testing
   - BPMN Linter
   - Rename Technical IDs
   - bpmn-js Token Simulation
   - Tooltip Plugin

**Comment by nikku** [comment]
Disable the [linter plug-in](https://github.com/camunda/camunda-modeler-linter-plugin), it is not compatible with latest modeler versions.

**Comment by talesmp** [comment]
Thanks, @nikku!

**Comment by hoya1101** [comment]
Hi, I met same issue. How to disable the linter plug-in?

**Comment by nikku** [comment]
The error log should allow you to start the modeler without plug-ins enabled. You may want to find the plug-ins in the [applications search paths](https://docs.camunda.io/docs/components/modeler/desktop-modeler/search-paths/) and remove it.
