### ISSUE TITLE
CamundA Modeler is not working

### ISSUE THREAD

**Issue by worldofkd** [camunda/camunda-modeler#3404]
### Describe the bug

[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:193:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///E:/camunda-modeler-5.7.0-win-x64/resources/app.asar/public/bundle.js:2:946340
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at setState (webpack://camunda-modeler-client/src/app/App.js:900:9)
    at setLintingState (webpack://camunda-modeler-client/src/app/App.js:877:9)
    at async file:///E:/camunda-modeler-5.7.0-win-x64/resources/app.asar/public/bundle.js:2:2643974 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml#) [ info ]
[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:181:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///E:/camunda-modeler-5.7.0-win-x64/resources/app.asar/public/bundle.js:2:946340
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at setState (webpack://camunda-modeler-client/src/app/App.js:900:9)
    at setLintingState (webpack://camunda-modeler-client/src/app/App.js:877:9)
    at async file:///E:/camunda-modeler-5.7.0-win-x64/resources/app.asar/public/bundle.js:2:2643974 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml#) [ info ]

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

Should open bpmn

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

**Comment by nikku** [comment]
@worldofkd Please provide necessary details (installed plug-ins, ...) so we can root cause your issue.

**Comment by philippfromme** [comment]
Likely due to an outdated version of the [linter plugin](https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin) that isn't compatible with new versions of the Camunda Modeler. What version of the Camunda Modeler are you using?
