### ISSUE TITLE
linter plugin shows error this.getModeler(...).get(...).setErrors is not a function

### ISSUE THREAD

**Issue by shenoy** [camunda/camunda-modeler#3507]
### Describe the bug

[C:\Camunda 7 Platform and Microservices Course\Exercise1_payment_process.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/bpmn/BpmnEditor.js:193:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///C:/camunda_installation_zip_extracted_files/resources/app.asar/public/bundle.js:2:920398
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&template=BUG_REPORT.yml#) [ info ]

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

I added the linter plugin to my plugins directory in modeler

### Environment

Windows 11

**Comment by nikku** [comment]
Duplicate, cf. [issues](https://github.com/camunda/camunda-modeler/issues?q=is%3Aissue+setErrors+is%3Aclosed+).
