### ISSUE TITLE
Cam Modeler 5.11.0 Crashed when using linter rules plugin

### ISSUE THREAD

**Issue by ganov** [camunda/camunda-modeler#3625]
### Describe the bug

Hi,
_Issue opened also here, please fell fre to close it if it's duplicate._

I used "camunda-modeler-custom-linter-rules-plugin" since Camunda Modeler 5.10.X and was working really great and we love it !
Unfortunately the plugin seem to occurs crash using it with the last version of Camunda Modeler V 5.11.0.

here is the error log i get :
[C:\Zzzzz\src\main\resources\ProcessusSimulation.bpmn] Cannot read properties of undefined (reading 'toLowerCase') at toLowerCase (webpack://camunda-modeler-client/src/app/tabs/panel/tabs/LintingTab.js:110:12) at file:///C:/Zzzzz/devtools/gpa-camunda-modeler-5.11.0-bugplugin/resources/app.asar/public/647.js:1:9839 at Array.sort (<anonymous>) at file:///C:/Zzzzz/devtools/gpa-camunda-modeler-5.11.0-bugplugin/resources/app.asar/public/647.js:1:9799 at reports (webpack://camunda-modeler-client/src/app/tabs/panel/tabs/LintingTab.js:54:18) at c (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:150:95) at file:///C:/Zzzzz/devtools/gpa-camunda-modeler-5.11.0-bugplugin/resources/app.asar/public/bundle.js:2:1098160 at a (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:232:24) at bi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:233:283) at ci (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:347) [ error ] This error may be the result of a plug-in compatibility issue. [ info ]

I would like to add that i only get the plugin working using the "original" plugin (from https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/) Maybe it is the reason why i get this error ?
if so, may you please provide the good way to add the official one into 5.11.0 cam modeler ?

Regards,
Ganov From Desjardins Group

### Steps to reproduce

1. use camunda modeler 5.11.0 with  camunda-modeler-linter-default-rules from https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/ or https://github.com/camunda/camunda-modeler-custom-linter-rules-plugin
2. open a BPMN containing bpmn rules errors 
3. click on bottom bar buttom to highlight bpmn rules errors 
4. Crash happenned

### Expected behavior

non craching plugin or modeler

### Environment

- OS: [Windows 10]
- Camunda Modeler Version 5.11.0
- Execution Platform: [e.g. Camunda Platform 7.19.X  based on Springboot ]
- Installed plug-ins: 
  - camunda-modeler-plugins=https://github.com/camunda/camunda-modeler-plugins/archive/refs/heads/master.zip
  - camunda-modeler-plugin-rename-technical-ids=https://github.com/camunda-community-hub/camunda-modeler-plugin-rename-technical-ids/archive/refs/heads/main.zip
  - camunda-modeler-token-simulation-plugin=https://github.com/camunda/camunda-modeler-token-simulation-plugin/archive/refs/heads/master.zip
  - camunda-modeler-property-info-plugin=https://github.com/mesoneer-ag/camunda-modeler-property-info-plugin/archive/refs/heads/master.zip
  - camunda-modeler-tooltip-plugin=https://github.com/viadee/camunda-modeler-tooltip-plugin/archive/refs/heads/main.zip
  - **camunda-modeler-linter-default-rules=https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/archive/refs/heads/main.zip**

### Additional context

I would like to add that i only get the plugin working using the "original" plugin (from https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/) Maybe it is the reason why i get this error ?
if so, may you please provide the good way to add the official one into 5.11.0 cam modeler ?

**Comment by ganov** [comment]
Hi,

Thx for your reply and your professional test.
I really was having bug using a specific bpmn. so i used cam Modeler only with the plugin, and it crashed again. 
I re design my Bpmn exactly the same way, and bug disappears. 

Nevertheless, If you want test with the bpmn that produced crash, here it is.

[ProcessusSimulation.bpmn.txt](https://github.com/camunda/camunda-modeler/files/11583247/ProcessusSimulation.bpmn.txt)

best regards

**Comment by barmac** [comment]
Thanks for sharing the BPMN. I believe the linter should not crash the application even with most unusual BPMN diagrams. I will have a look at your diagram and report back the results.

**Comment by barmac** [comment]
OK so the broken linter rule which crashed the Modeler was fixed via https://github.com/jonathanlukas/camunda-modeler-linter-default-rules/pull/16
If you update the plugin (`git pull && npm ci && npm run all`), Modeler should not crash even for the old diagram.

Nevertheless, a broken rule should not crash the application.

**Comment by barmac** [comment]
I created a follow-up issue: https://github.com/camunda/camunda-modeler/issues/3637
