### ISSUE TITLE
Linter Rules `camunda/implementation` fails when applying element template to Camunda 7 diagram

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/camunda-modeler#3630]
### Describe the bug

When applying an element template that creates `bpmn:extensionElements` to a model, the Modeler crashes. 

This happens as the rule `camunda/implementation` tries to call the method some on the `bpmn:extensionElements` node which does not exist.

```
rule <camunda/implementation> failed with error:  TypeError: extensionElements.some is not a function
    at hasConnector (implementation.js:63:1)
    at check (implementation.js:27:1)
    at r.enter (test-rule.js:70:30)
    at e (traverse.js:13:33)
    at traverse.js:29:13
    at Array.forEach (<anonymous>)
    at traverse.js:28:25
    at Array.forEach (<anonymous>)
    at e (traverse.js:23:25)
    at traverse.js:29:13
    at Array.forEach (<anonymous>)
    at traverse.js:28:25
    at Array.forEach (<anonymous>)
    at e (traverse.js:23:25)
    at e.exports (test-rule.js:69:3)
    at i.applyRule (linter.js:54:21)
    at linter.js:240:28
    at Array.forEach (<anonymous>)
    at linter.js:234:21
    at async $d.lint (Linter.js:61:11)
    at async op.lintTab (App.js:875:11)
    at async App.js:2315:7
```
This error is caught and written to the linter, but without an id of the element. On processing the reports on the linting tab, this leads to an exception when generating the report name.
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at B (LintingTab.js:110:13)
    at LintingTab.js:127:11
    at Array.sort (<anonymous>)
    at LintingTab.js:124:25
    at P (LintingTab.js:54:7)
    at Ho (react-dom.production.min.js:150:96)
    at wi (react-dom.production.min.js:166:273)
    at react-dom.production.min.js:179:453
    at Rs (react-dom.production.min.js:232:22)
    at Ns (react-dom.production.min.js:233:284)
    at xa (react-dom.production.min.js:249:348)
    at Ca (react-dom.production.min.js:248:144)
    at ga (react-dom.production.min.js:245:332)
    at qs (react-dom.production.min.js:243:86)
    at Object.enqueueSetState (react-dom.production.min.js:130:228)
    at C.setState (react.production.min.js:13:224)
    at op.setLintingState (App.js:900:10)
    at op.lintTab (App.js:877:10)
    at async App.js:2315:7
```

### Steps to reproduce

1. Use the element template inserted below
2. Apply it to a service task
3. The Modeler crashes

```json
{
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json",
    "id": "deepJavaNestedConnector",
    "name": "Deep Java Nested Connector",
    "appliesTo": [
        "bpmn:ServiceTask"
    ],
    "description": "This connector retrieves a Java Object from a variable, applies an input mapper, executes a function and applies an output mapper",
    "properties": [
        {
            "type": "Hidden",
            "value": "deepNestedConnector",
            "binding": {
                "type": "property",
                "name": "camunda:topic"
            }
        },
        {
            "type": "Hidden",
            "value": "external",
            "binding": {
                "type": "property",
                "name": "camunda:type"
            }
        },
        {
            "label": "Input Variable Name",
            "type": "String",
            "binding": {
                "type": "camunda:inputParameter",
                "name": "inputVariableName"
            }
        },
        {
            "label": "Input Data Mapper",
            "type": "String",
            "binding": {
                "type": "camunda:inputParameter",
                "name": "inputDataMapper"
            }
        },
        {
            "label": "Output Data Mapper",
            "type": "String",
            "binding": {
                "type": "camunda:inputParameter",
                "name": "outputDataMapper"
            }
        }
    ]
}
```

### Expected behavior

The linter should just run through and not crash the Modeler

### Environment

- OS: MacOS 13.3.1 (a)
- Camunda Modeler Version: 5.11.0
- Execution Platform: Camunda Platform
- Installed plug-ins: Some, but none is responsible

**Comment by philippfromme** [comment]
Can you share the diagram? The `implementation` rule shouldn't be used to lint Camunda 7 diagrams.

**Comment by jonathanlukas** [comment]
[failing-element-template.bpmn.txt](https://github.com/camunda/camunda-modeler/files/11563147/failing-element-template.bpmn.txt)

When applying the above provided template to this bpmn xml, the modeler breaks.

**Comment by nikku** [comment]
This is a bug we want to fix.

**Comment by nikku** [comment]
I've tried to reproduce this issue using the context you provided @jonathanlukas and failed:

* Loaded element template local to diagram
* Open diagram
* Apply template
* Things work like a charm

---

![image](https://github.com/camunda/camunda-modeler/assets/58601/1afa6943-a301-47d2-9303-4bb20514c752)

---

```xml

    <bpmn:serviceTask id="Activity_06jyj77" name="This task cannot have an element template applied" camunda:modelerTemplate="deepJavaNestedConnector" camunda:type="external" camunda:topic="deepNestedConnector">
      <bpmn:extensionElements>
        <camunda:inputOutput>
          <camunda:inputParameter name="inputVariableName" />
          <camunda:inputParameter name="inputDataMapper" />
          <camunda:inputParameter name="outputDataMapper" />
        </camunda:inputOutput>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_1cbjocq</bpmn:incoming>
    </bpmn:serviceTask>
```
