### ISSUE TITLE
Diagram with `isDefault` element template cannot be created

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3687]
### Describe the bug

Camunda Modeler 5 does not create a new diagram if a default template for a process is defined. The same behavior works in Camunda Modeler v4.x.

### Steps to reproduce

1. Configure a C7 default template for `bpmn:Process`
    
  ```json
  {
    "name": "ProcessDefaults",
    "id": "processFefaults",
    "description": "Default-Template for Process",
    "version": 1,
    "isDefault": true,
    "appliesTo": [
      "bpmn:Process"
    ],
    "properties": [
      {
        "label": "Demo Property Version-Tag",
        "type": "String",
        "value": "1",
        "editable": false,
        "description": "Demo Property",
        "binding": {
          "type": "property",
          "name": "camunda:versionTag"
        }
      }
    ]
  }
  ```
3. Create a new C7 diagram
4. See that diagram fails to create; the log reports an (uncaught) exception:

  ```plain
  Error: command required
      at CommandStack.execute (CommandStack.js:178:1)
      at index.esm.js:1851:1
      at forEach (index.esm.js:246:1)
      at MultiCommandHandler.preExecute (index.esm.js:1850:1)
      at CommandStack._internalExecute (CommandStack.js:438:1)
      at CommandStack.execute (CommandStack.js:186:1)
      at applyDefaultTemplates (applyDefaultTemplates.js:30:1)
      at PlatformBpmnModeler.invoke (index.esm.js:226:1)
      at BpmnEditor.handleImport (BpmnEditor.js:382:1)
      at BpmnEditor.importXML (BpmnEditor.js:577:1)
```

### Expected behavior

* [x] Process is created with properties defined in `isDefault` template. :arrow_right: https://github.com/camunda/camunda-modeler/pull/3690
* [x] Exception is logged in the appropriate places (log panel) :arrow_right: https://github.com/camunda/camunda-modeler/pull/3691

### Environment

- OS: Linux
- Camunda Modeler Version: v5.12.1
- Execution Platform: Camunda Platform 7
- Installed plug-ins: None

### Additional context

Reported via SUPPORT-17420.

**Comment by nikku** [comment]
Addressed via https://github.com/camunda/camunda-modeler/pull/3690.

**Comment by nikku** [comment]
Additional fix for error handling: https://github.com/camunda/camunda-modeler/pull/3691.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/commit/b9c4514db693178f29cd4c07976145bea9282510.
