### ISSUE TITLE
Cannot remove process element template

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3688]
### Describe the bug

If I try to remove the element template from the process root then the modeler fails with an exception:

```
[diagram_2.bpmn] Cannot read properties of undefined (reading 'children')
    at BpmnOrderingProvider.getOrdering (webpack://camundanode_modules/bpmn-js/lib/features/ordering/BpmnOrderingProvider.js:153:0)
    at file://[...]camunda-modeler/client/build/vendors-node_modules_bpmn-io_add-exporter_index_js-node_modules_bpmn-io_variable-resolver_lib-d3890a.js:40571:25
    at invokeFunction (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:580:0)
    at EventBus._invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:0)
    at EventBus._invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:0)
    at EventBus.fire (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:0)
    at CommandStack._fire (webpack://camundanode_modules/diagram-js/lib/command/CommandStack.js:395:0)
    at CommandStack._internalExecute (webpack://camundanode_modules/diagram-js/lib/command/CommandStack.js:435:0)
    at CommandStack.execute (webpack://camundanode_modules/diagram-js/lib/command/CommandStack.js:186:0)
    at Modeling.createShape (webpack://camundanode_modules/diagram-js/lib/features/modeling/Modeling.js:397:0) [ error ]
```

### Steps to reproduce

1. Configure a [process template](https://github.com/camunda/camunda-modeler/files/11915072/process-is-default-c7.json.txt) and [open test diagram](https://github.com/camunda/camunda-modeler/files/11915060/c7-diagram.bpmn.txt) (also works for [C8 process template](https://github.com/camunda/camunda-modeler/files/11915076/process-is-default-c8.json.txt) + [diagram](https://github.com/camunda/camunda-modeler/files/11915082/c8-diagram.bpmn.txt))
4. Remove template through the properties panel
5. See editor blowing up with `Cannot read properties of undefined`

### Expected behavior

* I can remove a process template _or_ removing is disabled

### Environment

- OS: Linux
- Camunda Modeler Version: v5.12.1
- Execution Platform: Camunda Platform 7, Camunda Cloud / Camunda Platform 8
- Installed plug-ins: None

### Additional context

Related to https://github.com/camunda/camunda-modeler/issues/3687

**Comment by marstamm** [comment]
**Root cause**
We use `replace` to remove templates. This is not possible with root elements because replacing elements requires a parent element to be present.

Related bug: it is not possible to remove a default template, because when the "new" element is created, the default template is applied again. Will fix this as well
