### ISSUE TITLE
Form deployment disappears after error

### ISSUE THREAD

**Issue by marstamm** [camunda/camunda-modeler#3979]
### Describe the bug

![image](https://github.com/camunda/camunda-modeler/assets/21984219/bfc47fcf-e867-4ff2-980b-e2e3497312d9)

Sentry Issue: [CAMUNDA-MODELER-KEE](https://camunda-modeling.sentry.io/issues/4620313336/?referrer=github_integration)

```
TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
  at U.getStyle (/build/bundle.js:2:423718)
  at U.render (/build/bundle.js:2:424306)
  at Ti (/build/bundle.js:2:170947)
  at Pi (/build/bundle.js:2:170742)
  at None (/build/bundle.js:2:195731)
...
(10 additional frame(s) were not displayed)
```

### Steps to reproduce

Unknown at this point, check Sentry issue for stack trace + previous user interactions 

### Expected behavior

The Deploy button is displayed
![image](https://github.com/camunda/camunda-modeler/assets/21984219/a698e937-bd79-4459-907b-7adb88981823)

### Environment

 * Version: 5.17.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: Form - Camunda 8

### Additional context

Found by @GeethaParthasarathy during release testing

**Comment by philippfromme** [comment]
Unfortunately, I can't reproduce this issue. Moving to backlog until we have more users impacted.
