### ISSUE TITLE
Crash after external update 

### ISSUE THREAD

**Issue by sam58** [camunda/camunda-modeler#4015]
### Describe the bug

Crash after update in external editor. The bug is floating

### Steps to reproduce

1. open modeller . Open bpmn process for 7 version
2. open this process in Intelij Idea. Edit the process manually 
3. go to modeller. Modeller show warnin "The file has been changed externally. Would tou like to reload it?
4. after answer "reload" do crash modeller

### Expected behavior

C:\dev\asc_icode_back\src\main\resources\bpmn\asc_ctd_process.bpmn] (intermediate value)(...).get is not a function
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/bundle.js:2:381911
    at Array.reduce (<anonymous>)
    at reduce (webpack://camundanode_modules/@camunda/linting/lib/utils/properties-panel.js:27:17)
    at this (webpack://camundanode_modules/@camunda/linting/lib/modeler/Linting.js:76:24)
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/639.js:1:9928
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/619.js:2:27938
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:23)
    at fire (webpack://camundanode_modules/diagram-js/lib/features/selection/Selection.js:123:17) [ error ]
[C:\dev\asc_icode_back\src\main\resources\bpmn\asc_ctd_process.bpmn] (intermediate value)(...).get is not a function
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/bundle.js:2:381911
    at Array.reduce (<anonymous>)
    at reduce (webpack://camundanode_modules/@camunda/linting/lib/utils/properties-panel.js:27:17)
    at this (webpack://camundanode_modules/@camunda/linting/lib/modeler/Linting.js:76:24)
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/639.js:1:9928
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/619.js:2:27938
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:23)
    at fire (webpack://camundanode_modules/diagram-js/lib/features/selection/Selection.js:123:17) [ error ]
[C:\dev\asc_icode_back\src\main\resources\bpmn\asc_ctd_process.bpmn] (intermediate value)(...).get is not a function
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/bundle.js:2:381911
    at Array.reduce (<anonymous>)
    at reduce (webpack://camundanode_modules/@camunda/linting/lib/utils/properties-panel.js:27:17)
    at this (webpack://camundanode_modules/@camunda/linting/lib/modeler/Linting.js:76:24)
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/639.js:1:9928
    at file:///C:/dev/camunda-modeler-5.17.0-win-x64/resources/app.asar/public/619.js:2:27938
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:345:23)
    at fire (webpack://camundanode_modules/diagram-js/lib/features/selection/Selection.js:123:17)

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.17.0
- Execution Platform: e.g. Camunda 7

**Comment by barmac** [comment]
What changes did you introduce? Can you share the diagram?

**Comment by nikku** [comment]
Closing this issue due to missing feedback.
