### ISSUE TITLE
Error when removing an element template

### ISSUE THREAD

**Issue by ceschu** [camunda/camunda-modeler#4113]
### Describe the bug

When removing an element template from a service or user task or intermediate event (and probably others), an error is thrown. 

```
[C:\Users\ceschu\Documents\test.bpmn] Cannot read properties of undefined (reading 'type')
    at file:///C:/Users/ceschu/camunda-modeler-5.19.0/resources/app.asar/public/274.js:180:48134
    at file:///C:/Users/ceschu/camunda-modeler-5.19.0/resources/app.asar/public/274.js:23:171398
    at file:///C:/Users/ceschu/camunda-modeler-5.19.0/resources/app.asar/public/274.js:23:99574
    at listener (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/core/EventBus.js:423:33)
    at _invokeListener (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/core/EventBus.js:397:23)
    at _invokeListeners (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/core/EventBus.js:345:23)
    at fire (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/command/CommandStack.js:395:28)
    at _fire (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/command/CommandStack.js:435:9)
    at _internalExecute (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/command/CommandStack.js:186:7)
    at execute (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/features/modeling/Modeling.js:573:21) [ error ]
```

### Steps to reproduce

1. Model any element in a bpmn diagram
2. Create any element template
3. Apply template to element
4. Remove template (not unlink)
5. Error is thrown

### Expected behavior

Element template can be removed, unlinking element and template and deleting applied properties.

### Environment

- OS: Windows 10
- Camunda Modeler Version: 5.19.0
- Execution Platform: Camunda 7

### Additional context

This happens for my Camunda modeler v 5.19.0, but not for my v 5.13.0 version, using the same templates. It happens with different templates for different element types. It is the same error with every template.

In the XML file, I can see that the unlinking does not work - after the error, the template and its properties are still on the element it was applied to.

This issue seems to be similar/related to https://github.com/camunda/camunda-modeler/issues/2128 and https://github.com/camunda/camunda-modeler/issues/1990 but the error is still different.

**Comment by nikku** [comment]
Please try the latest nightly. It should be fixed there and in the soon to be release v5.20.0 version of the app.

Originally reported via https://github.com/camunda/camunda-modeler/issues/4070.
