### ISSUE TITLE
Error is thrown when process-related problem is clicked in a collaboration diagram

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4158]
### Describe the bug

This error is thrown when I click a process-related problem in a collaboration diagram:

```
rootElement required
    at Canvas.setRootElement (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/core/Canvas.js:784:0)
    at Canvas.scrollToElement (webpack://camundanode_modules/bpmn-js/node_modules/diagram-js/lib/core/Canvas.js:1253:0)
    at Linting.showError (webpack://camundanode_modules/@camunda/linting/lib/modeler/Linting.js:27:0)
    at BpmnEditor.triggerAction (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:698:0)
    at MultiSheetTab.triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:0)
    at EditorTab.triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:0)
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/client/build/bundle.js:53557:16
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/client/build/bundle.js:53934:20
    at file:///Users/maciej/workspace/bpmn-io/camunda-modeler/client/build/bundle.js:57076:7
    at HTMLUnknownElement.callCallback (webpack://camundanode_modules/react-dom/cjs/react-dom.development.js:188:0) [ error ]
```

### Steps to reproduce

https://github.com/camunda/camunda-modeler/assets/28307541/99cc2a0a-fd13-4654-9452-689d4aba36c3

### Expected behavior

No error is thrown and a respective participant is selected.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

**Comment by nithinssabu** [comment]
> Did you spot something similar in Web Modeler?

Yes and it generated 16k events in the last 30 days.
https://modeler.sentry.io/issues/4436962339/?project=6167265&query=is%3Aarchived&referrer=issue-stream&statsPeriod=7d&stream_index=1

https://github.com/camunda/web-modeler/issues/7801

**Comment by nikku** [comment]
PR welcome if you want to investigate a fix. :)

**Comment by philippfromme** [comment]
We broke it with this https://github.com/camunda/linting/pull/78. 🤡

**Comment by nikku** [comment]
You build it, you break it :see_no_evil:

**Comment by nikku** [comment]
Fixed upstream via https://github.com/camunda/linting/pull/104. @philippfromme Do you look into integrating this?

**Comment by nikku** [comment]
@philippfromme Is there stuff missing to get this integrated / merged in Desktop Modeler?

**Comment by philippfromme** [comment]
Will be integrated before the 5.23 release.
