### ISSUE TITLE
"appendElement is not a registered action" with new context pad

### ISSUE THREAD

**Issue by barmac** [camunda/camunda-modeler#4349]
### Describe the bug

The new context pad broke the "A" shortcut for create anything. The following error is reported:

```
appendElement is not a registered action
    at s (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:266:9)
    at error (webpack://camundanode_modules/diagram-js/lib/features/editor-actions/EditorActions.js:175:10)
    at trigger (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:709:40)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/MultiSheetTab.js:269:18)
    at triggerAction (webpack://camunda-modeler-client/src/app/tabs/EditorTab.js:36:33)
    at file:///Users/maciej/Desktop/rc/Camunda%20Modeler%202.app/Contents/Resources/app.asar/public/bundle.js:2:3598876
    at fn (webpack://camunda-modeler-client/src/app/App.js:2448:19)
    at file:///Users/maciej/Desktop/rc/Camunda%20Modeler%202.app/Contents/Resources/app.asar/public/bundle.js:2:3603414
    at exec (webpack://camunda-modeler-client/src/app/AppParent.js:76:11)
    at onAction (webpack://camunda-modeler-client/src/app/KeyboardBindings.js:161:6) [ error ]

```

### Steps to reproduce

1. Enable flag for the new context pad
2. Press "A"
3. now this happens

### Expected behavior

No error is reported and create anything menu opens

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: v5.24.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: `--enable-new-context-pad`

**Comment by philippfromme** [comment]
Note that this error only occurs in the Desktop Modeler. It works in `@camunda/improved` canvas and in the web modeler.

**Comment by nikku** [comment]
Let's investigate this and potentially fix as a minor follow-up. Moving to `ready`.

**Comment by barmac** [comment]
In the improved-canvas library, we [register `appendCreatePad` action](https://github.com/camunda/improved-canvas/blob/9c8a56835886772d3bf9320b0ec186ae7d39a5e5/lib/bpmn/appendCreatePad/AppendEditorActions.js#L40), and [deregister `appendElement`](https://github.com/camunda/improved-canvas/blob/9c8a56835886772d3bf9320b0ec186ae7d39a5e5/lib/bpmn/appendCreatePad/AppendEditorActions.js#L20). Somehow the latter action is still kept for the keyboard binding though.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler/issues/4408.
