### ISSUE TITLE
issue while using the linter in camunda modeler

### ISSUE THREAD

**Issue by Vinod1991d** [camunda/camunda-modeler#4353]
### Describe the bug

issue while using the linter in camunda modeler

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

it should lint properly the workflow

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

issue while using the linter in camunda modeler

getting following issue

[diagram_1.bpmn] this.getModeler(...).get(...).setErrors is not a function
    at setErrors (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:180:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///C:/Users/10697057/Downloads/camunda-modeler-5.15.2-win-x64/resources/app.asar/public/bundle.js:2:206112
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at file:///C:/Users/10697057/Downloads/camunda-modeler-5.15.2-win-x64/resources/app.asar/public/bundle.js:2:3443304 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yml#) [ info ]

**Comment by nikku** [comment]
Cf. https://github.com/camunda/camunda-modeler/issues?q=is%3Aissue+%22setErrors+is+not+a+function%22+is%3Aclosed.
