### ISSUE TITLE
dev snapshot: registry entries seem to be created with the wrong target

### ISSUE THREAD

**Issue by GitMensch** [camunda/camunda-modeler#643]
~~~
app:client-ready
[workspace] save
Window focused
[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\shell\open\command /d "\"C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe\" -- \"%1\"" /f
Der Vorgang wurde erfolgreich beendet.

[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.bpmn\DefaultIcon /d "C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe,0" /f
Der Vorgang wurde erfolgreich beendet.

[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.dmn\shell\open\command /d "\"C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe\" -- \"%1\"" /f
Der Vorgang wurde erfolgreich beendet.

[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.dmn\DefaultIcon /d "C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe,0" /f
Der Vorgang wurde erfolgreich beendet.

[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.cmmn\shell\open\command /d "\"C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe\" -- \"%1\"" /f
Der Vorgang wurde erfolgreich beendet.

[file associations] exec
> reg ADD HKEY_CURRENT_USER\Software\Classes\.cmmn\DefaultIcon /d "C:\dev\camunda-modeler.git\node_modules\electron\dist\electron.exe,0" /f
Der Vorgang wurde erfolgreich beendet.
~~~

A double click on a bpmn (opening it with a `npm run dev` works fine) result in

~~~
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
C:\dev\test\src\main\resources\BPMN\PROC_test.bpmn:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { <?xml version="1.0" encoding="UTF-8"?>
                                                                                                                                                           ^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (C:\dev\camunda-modeler.git\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (C:\dev\camunda-modeler.git\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (C:\dev\camunda-modeler.git\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)

[OK]
~~~

Is there anything I can fix?

**Comment by nikku** [comment]
Would be interesting if other Windows users experience the same issues.

**Comment by philippfromme** [comment]
This only affects development mode.
