### ISSUE TITLE
Sometimes error when placing bpmn elements on each other 

### ISSUE THREAD

**Issue by felix-mueller** [camunda/camunda-modeler#727]
In the new 1.12.0-alpha2 when I want to model a diagram
and I place bpmn elements on each other, sometimes the log opens and shows:
`
TypeError: Cannot read property 'x' of undefined
    at isPointInsideBBox (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27654:16)
    at insertShape (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27704:12)
    at file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27774:7
    at file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:79932:15
    at invokeFunction (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82227:13)
    at EventBus._invokeListener (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82129:19)
    at EventBus._invokeListeners (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82117:24)
    at EventBus.fire (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82081:24)
    at CommandStack._fire (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:80363:29)
    at CommandStack._internalExecute (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:80437:10)  [error]
TypeError: Cannot read property 'x' of undefined
    at isPointInsideBBox (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27654:16)
    at insertShape (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27704:12)
    at file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:27774:7
    at file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:79932:15
    at invokeFunction (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82227:13)
    at EventBus._invokeListener (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82129:19)
    at EventBus._invokeListeners (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82117:24)
    at EventBus.fire (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:82081:24)
    at CommandStack._fire (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:80363:29)
    at CommandStack._internalExecute (file:///private/var/folders/75/hk69zssn0j998mkp524g_0f00000gn/T/AppTranslocation/3E812149-50AA-4CA0-AE39-5E1AB101AF2E/d/CamundaModeler.app/Contents/Resources/app.asar/public/index.js:80437:10)  [error]
`

**Comment by nikku** [comment]
Which elements do you try to place onto each other? We'd need some way to reproduce your report.

**Comment by nikku** [comment]
May this be related to https://github.com/bpmn-io/diagram-js/issues/245?

**Comment by felix-mueller** [comment]
I only used exclusive gateways and tasks. This does not always happen, but I was able to reproduce it a few times.
What I did was:
1. Auto-Place a Task using the Context Menu after Start Event
2. Auto-Place an Exclusive Gateway after Task using Context Menu
3. Auto-Place a Task after Exclusive Gateway using Context Menu
4. Place an Exlusive Gateway right next to the first task (on edge of task)
5. Try to move this exclusive gateway to right

<img width="1093" alt="screen shot 2018-02-05 at 09 27 11" src="https://user-images.githubusercontent.com/20283848/35794711-10685820-0a57-11e8-94ec-aaf6e723ab0c.png">

**Comment by philippfromme** [comment]
You can reproduce this by dropping an element onto another element while the mouse cursor is on a sequence flow. This will trigger drop-on-flow behavior which then fails.

![foobar](https://user-images.githubusercontent.com/7633572/36160580-d537431a-10e1-11e8-97cf-d8eedcbf86e4.gif)

**Comment by felix-mueller** [comment]
awesome - thanks for quick fix!
