### ISSUE TITLE
TypeError when using lasso tool outside of app

### ISSUE THREAD

**Issue by TilmanK** [camunda/camunda-modeler#807]
I'm receiving a 100% reproducible TypeError when doing the following:

Using any bpmn diagram (also works with a default one with only the start event) I use the lasso tool to mark any content. When I pull the lasso tool (mouse left key pressed) outside the application window, I get the following error:

```
TypeError: originalEvent.target.parentNode.getAttribute is not a function
    at ToolManager.<anonymous> (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:100070:75)
    at invokeFunction (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:85139:13)
    at EventBus._invokeListener (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:85043:19)
    at EventBus._invokeListeners (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:85031:24)
    at EventBus.fire (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:84995:24)
    at fire (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:89816:21)
    at end (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:89914:5)
    at HTMLDocument.trapClickAndEnd (file:///C:/ProgramFiles/camunda-modeler/resources/app.asar/public/index.js:89950:5)  [error]
```

Attached to screenshots. Please note, that you can't see the mouse cursor on the first picture.
![lasso_tool](https://user-images.githubusercontent.com/8856390/40407059-6679dc4c-5e63-11e8-9160-0200306b2d70.png)
![type_error](https://user-images.githubusercontent.com/8856390/40407061-66ba5e02-5e63-11e8-953e-b41ad2953831.PNG)

**Comment by nikku** [comment]
Does the error prevent you from using the application afterwards?

**Comment by TilmanK** [comment]
Hi nikku,

I havent't found any restrictions in the latter usage.

Best Regards

Tilman

**Comment by philippfromme** [comment]
Closed via https://github.com/bpmn-io/diagram-js/commit/31db1bf30acdb829222cf6174f77e15a801080d8.
